### PR TITLE
refactor(batch): Use futures-async-stream to implement values executor

### PR DESCRIPTION
**Pull request by D2Lark**
## What's changed and what's your intention?

Implement Value using Executor2 trait.

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)
close https://github.com/singularity-data/risingwave/issues/1946

### CODE REVIEW

**Comment by D2Lark** [comment]
Hi, this is my first PR at RW, so I'm not that familiar with CI. From the error reported it seems that I need to provide the aws runner key? I've run cargo fmt ,cargo clippy, cargo check and cargo test locally without this problem, what do I need to do?

**Comment by skyzh** [comment]
In fact, the workflow has been run twice -- once without sufficient permission, and once with permission. These two are real failed cases:

image

Seems that e2e test failed. May take a look at https://github.com/singularity-data/risingwave/blob/main/CONTRIBUTING.md#end-to-end-testing and fix the bugs.

**Review by liurenjie1024 — APPROVED** [review]
Thanks for your contribution! LGTM

**Comment by D2Lark** [comment]
I found that values executor2 could pass the e2e test, then I logged inside project executor2 and got this error message via computer-node.log, which should have been printed when running the tpch-q1 test.

> 2022-04-20T12:48:20.225571Z  INFO risingwave_batch::executor::row_seq_scan: Table scan closed.    
> 2022-04-20T12:48:20.232262Z DEBUG risingwave_batch::executor2::projection: get_chunk    

> thread 'tokio-runtime-worker' panicked at 'Should not serialize str for hash!', src/common/src/hash/key.rs:349:9
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/f4a7ce997a1d7546d2b737f8b87d36907bcea2ad/library/std/src/panicking.rs:584:5
>    1: core::panicking::panic_fmt
>              at /rustc/f4a7ce997a1d7546d2b737f8b87d36907bcea2ad/library/core/src/panicking.rs:142:14
>    2: <&str as risingwave_common::hash::key::HashKeySerDe>::serialize
>              at ./src/common/src/hash/key.rs:349:9
>    3: <risingwave_common::hash::key::FixedSizeKeySerializer<_> as risingwave_common::hash::key::HashKeySerializer>::append
>              at ./src/common/src/hash/key.rs:474:28
>    4: risingwave_common::hash::key::serialize_array_to_hash_key
>              at ./src/common/src/hash/key.rs:575:9
>    5: risingwave_common::hash::key::<impl risingwave_common::array::ArrayImpl>::serialize_to_hash_key
>              at ./src/common/src/hash/key.rs:602:9
>    6: risingwave_common::hash::key::HashKey::build_from_hash_code
>              at ./src/common/src/hash/key.rs:110:13
>    7: risingwave_common::hash::key::HashKey::build
>              at ./src/common/src/hash/key.rs:96:9


My idea: commit valued executor2 first, but need to comment out projection executor's unit test using value executor2.
If I figure out why projection crashes I'll submit a new PR

**Comment by D2Lark** [comment]
> Please don't comment out ut in projection executor. In fact we have provided Executor2Wrapper to covert Executor2 to Executor, and you can use that.

Thanks! now I understand the How to migrate executorv1 to executorv2. I'll try to carry the rest of the executor, starting with the simpler ones 🤪

**Comment by D2Lark** [comment]
> [END] e2e_test/v2/streaming/tpch_snapshot.slt                .. [OK] in 58208 ms
> [cargo-make] INFO - Build Done in 106.34 seconds.

I have passed the e2e test on my local env. Why the latest change has failed ci result 🤪 ?

**Comment by TennyZhuang** [comment]
bors try

**Comment by TennyZhuang** [comment]
Sorry but currently we need to use bors to run CI for PRs from forks.

https://github.com/singularity-data/risingwave/runs/6104889763?check_suite_focus=true

It seems that your clippy check is failed.

**Comment by liurenjie1024** [comment]
According to the log it seems that clippy check not passed yet, please refer to this: https://github.com/singularity-data/risingwave/blob/main/CONTRIBUTING.md#lint

**Comment by liurenjie1024** [comment]
bors try

**Comment by liurenjie1024** [comment]
bors try

**Comment by liurenjie1024** [comment]
bors try

**Comment by D2Lark** [comment]
> Sorry but currently we need to use bors to run CI for PRs from forks.

My understanding is that because I am PR from fork, I have to type bors try before the CI is actually executed?

**Comment by liurenjie1024** [comment]
> > Sorry but currently we need to use bors to run CI for PRs from forks.
> 
> My understanding is that because I am PR from fork, I have to type bors try before the CI is actually executed?

Yes, but it seems that there are some bugs in our config, we'll fix later.

**Comment by D2Lark** [comment]
> bors try

This looks a bit FUNNY 😂

**Comment by liurenjie1024** [comment]
bors try

**Pull request merged**
