### PR TITLE
chore(relational_layer): add value_meta in relational write interfaces

### PR DESCRIPTION
**Pull request by wcy-fdu**
## What's changed and what's your intention?

As title, relational layer provides hash and non-hash write interfaces.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

### CODE REVIEW

**Review by xx01cyx — APPROVED** [review]
LGTM. But I think an alternative is to have an `inner` method with a flag param indicating whether value meta needs computing, like:

```rust
fn batch_write_rows_inner(..., stateful_flag: bool) -> StorageResult<()> {
    ...
    if stateful_flag {
        // compute value meta
    }
}
```

and call this inner method in `batch_write_rows` and `batch_write_rows_inner` to make the code clearer.

**Comment by xx01cyx** [comment]
But since it is a storage write API, maybe we should put efficiency first and reduce unnecessary function call and `if` branch...

**Comment by wcy-fdu** [comment]
> 


> But since it is a storage write API, maybe we should put efficiency first and reduce unnecessary function call and `if` branch...

I prefer reduce unnecessary `if`  judgment, which may pass a `stateful_flag ` while write to storage.

**Comment by skyzh** [comment]
Two small issues:
* value meta isn't always pk. Should have another option to specify column ids (or column indices) of value meta.
* `batch_write_rows_with_value_meta` seems to have a lot of code in common with `batch_write_rows`. Maybe we can do some deduce.

**Comment by skyzh** [comment]
If you are interested, you may also refactor MaterializeExecutor to use distribution key for value meta.

https://github.com/singularity-data/risingwave/issues/1971

**Pull request merged**
