### PR TITLE
feat(streaming): report create mv progress continuously

### PR DESCRIPTION
**Pull request by BugenZhao**
## What's changed and what's your intention?

The continuation of #2773 in the streaming part. Besides, we switch to an additional `done` field to the progress in the protobuf definition instead of implying by `consumed_epoch == curr_epoch` due to some race cases of rearranged chain.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)
- #2773
- #2691

### CODE REVIEW

**Review by yezizp2012 — APPROVED** [review]
LGTM

**Review by skyzh — APPROVED** [review]

**Comment by skyzh** [comment]
May also help reduce the default log limit in `Makefile.toml`. Maybe we can now set the upper limit to few KBs.

**Comment by lmatz** [comment]
seems repetitively fail on the step of killing cluster

**Comment by skyzh** [comment]
Too many logs for batch queries 🤣

log size is significantly large (1.4M). Please disable unnecessary logs.

**Pull request merged**
