### PR TITLE
feat(storage): store compaction group id in SST meta

### PR DESCRIPTION
**Pull request by zwang28**
**Please don't review the code for now. May have some design change.**

### CODE REVIEW

**Comment by Little-Wallace** [comment]
If we store these sst files in defferent group, it seems that we do not need to store compaction group id in sst meta?

**Comment by zwang28** [comment]
> If we store these sst files in defferent group, it seems that we do not need to store compaction group id in sst meta?

I think we still need to know which group a SST belongs to, when commit_epoch.

**Comment by hzxa21** [comment]
> If you mean SstableInfo, I think we need know which group a SST belongs to, when commit_epoch. Though storing id in SstableInfo is not the only way to do it.

If the version and shared buffer are already separated by compaction group, how about also separating SSTs passed in commit_epoch by compaction group id (e.g. a vec of (table_id, SSTs)). In this case, we don't need to modify Sstableinfo.

**Comment by zwang28** [comment]
Design changed.

**Pull request closed without merging**
