### PR TITLE
feat(frontend): support filter clause in aggregation

### PR DESCRIPTION
**Pull request by Enter-tainer**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

### Summarize your change
This PR adds [selective aggregation](https://modern-sql.com/feature/filter) support to the frontend.
### How does this PR work?
To parse the selective aggregation syntax, the parser, the binder, and the `logical_agg` plan node have been changed.

- The column prune of `LogicalAgg` is changed as well to preserve columns that are referred to by the filter clause.
- When performing 2 phase aggregation, only the `partial_agg` needs `filter`. 

### Limitations of the Current Code
1. Since the parser and the AST is changed, `sqlsmith` is changed as well. But currently, it can only generate aggregation functions without any filter.
2. An extra field `is_in_filter_clause` is added in `LogicalAggBuilder` because the filter clause can refer to any columns while other places can only refer to group keys. So I add this field to distinguish between them. IMO the current implementation is kind of dirty.
- Add the 'user-facing changes' label if your PR contains changes that are visible to users (optional)

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## TODO

- [x] add more tests & check corner cases
- [x] filter clause should be taken into account in `rewrite_with_input` 

## Refer to a related PR or issue link (optional)
Tracking in #3589, RFC #3506

## Future works

After adding selective aggregation in the frontend, I will continue working to add this function to the executors.

### CODE REVIEW

**Review by st1page — DISMISSED** [review]
generally LGTM. the planner tests are comprehensive, good work!

**Review by likg227 — APPROVED** [review]
LGTM

**Review by st1page — COMMENTED** [review]
should check if exist aggregation in the filter clause.
test on PG:
```
dev=# explain select max(v2) filter(where min(v3) > 1.0) from test group by v1;
ERROR:  aggregate functions are not allowed in FILTER
LINE 1: explain select max(v2) filter(where min(v3) > 1.0) from test...
```

**Review by st1page — APPROVED** [review]
LGTM

**Pull request merged**
