### PR TITLE
(draft) binder: Bind nested joins

### PR DESCRIPTION
**Pull request by jon-chuang**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
Bind nested joins
Depends on the lateral_context defined in https://github.com/singularity-data/risingwave/pull/3788

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
Closes: https://github.com/singularity-data/risingwave/issues/3816

### CODE REVIEW

**Comment by jon-chuang** [comment]
Seems that nested joins need to take into account a hack for looking for columns via table name: https://github.com/singularity-data/risingwave/pull/3851#discussion_r921885348

Is a possible workaround to assign anonymous table names to the nested joins?

**Comment by xiangjinwu** [comment]
> recursively obtain the table name

According to discussion on the natural join PR, there may be pseudo columns without table name. Based on my current understanding, the method of "finding table name and **binding qualified column**" is in the wrong direction. It was a hack we did for `join-using` when we lack the ability to separate contexts from left and right table.

Now that we have `{push,pop}_lateral_context` and a way to merge them, we could just **bind the unqualified column** in left and right context separately.

This complexity actually comes from `join-using` and `natural-join`. Let's focus on the discussion of better context API in that PR and come back later. Nested join would be trivial at that time.

**Comment by jon-chuang** [comment]
> Now that we have {push,pop}_lateral_context and a way to merge them, we could just bind the unqualified column in left and right context separately.

Yes, that is one way but I found it could be quite verbose and annoying to manually bind the columns rather than call `bind_expr`, on the correctly identified columns, which is why I went with a placeholder table name after all in https://github.com/singularity-data/risingwave/pull/4349

I think doing a recursive eval of table name in the unambiguous case and disambiguating when column is in a group is a reasonable solution.

**Comment by jon-chuang** [comment]
Btw, just as a reference, this is how postgres resolves the folllowing query:

```sql
postgres=# explain verbose select *, t1.x, t2.x, t3.x, x from t1 full join (t2 full join t3 using (x)) using (x);
                                               QUERY PLAN                                               
--------------------------------------------------------------------------------------------------------
 Merge Full Join  (cost=3476.34..9707.01 rows=414528 width=20)
   Output: COALESCE(t1.x, COALESCE(t2.x, t3.x)), t1.x, t2.x, t3.x, COALESCE(t1.x, COALESCE(t2.x, t3.x))
   Merge Cond: (t1.x = (COALESCE(t2.x, t3.x)))
   ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
         Output: t1.x
         Sort Key: t1.x
         ->  Seq Scan on public.t1  (cost=0.00..35.50 rows=2550 width=4)
               Output: t1.x
   ->  Sort  (cost=3296.56..3377.84 rows=32512 width=8)
         Output: t2.x, t3.x, (COALESCE(t2.x, t3.x))
         Sort Key: (COALESCE(t2.x, t3.x))
         ->  Merge Full Join  (cost=359.57..860.00 rows=32512 width=8)
               Output: t2.x, t3.x, COALESCE(t2.x, t3.x)
               Merge Cond: (t2.x = t3.x)
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Output: t2.x
                     Sort Key: t2.x
                     ->  Seq Scan on public.t2  (cost=0.00..35.50 rows=2550 width=4)
                           Output: t2.x
               ->  Sort  (cost=179.78..186.16 rows=2550 width=4)
                     Output: t3.x
                     Sort Key: t3.x
                     ->  Seq Scan on public.t3  (cost=0.00..35.50 rows=2550 width=4)
                           Output: t3.x
```

**Comment by jon-chuang** [comment]
Closed in favour of: https://github.com/singularity-data/risingwave/pull/4401

**Pull request closed without merging**
