### PR TITLE
refactor: remove vnode_mappings in CompactTask and GroupedSstableBuilder

### PR DESCRIPTION
**Pull request by hzxa21**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

- Remove vnode_mappings in CompactTask since it is always empty.
- Remove VirtualNodeGrouping for GroupedSstableBuilder since we abandon consistent hash aware compaction.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

### CODE REVIEW

**Comment by Li0k** [comment]
can we remove the code of GroupedSstableBuilder ? (replaced by CapacitySplitTableBuilder)

**Comment by hzxa21** [comment]
> can we remove the code of GroupedSstableBuilder ? (replaced by CapacitySplitTableBuilder)

I added a TODO for this already. Need to check with @zwang28 whether GroupedSstableBuilder based on compaction group will be needed.

**Comment by zwang28** [comment]
> > can we remove the code of GroupedSstableBuilder ? (replaced by CapacitySplitTableBuilder)
> 
> I added a TODO for this already. Need to check with @zwang28 to confirm whether GroupedSstableBuilder based on compaction group will be needed.

Compaction group doesn't rely on GroupedSstableBuilder. So please help to remove it. @Li0k

**Review by zwang28 — APPROVED** [review]

**Comment by hzxa21** [comment]
GroupedSstableBuilder removed.

**Pull request merged**
