### PR TITLE
fix: use SomeShard as the distribution of batch scan

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
For other batch operators, `HashShard` is a simple hashing, i.e.,
`target_shard = hash(dist_key) % shard_num`

But MV is actually sharded by consistent hashing, i.e.,
`target_shard = vnode_mapping.map(hash(dist_key) % vnode_num)`

They are incompatible, so we just specify its distribution as `SomeShard` to force an exchange is inserted.

To reproduce the current wrong behavior:
```sql
create table t(x int);
create index i on t(x);
insert into t values (1),(2),(3),(4),(5);

explain select * from t join i using(x);
                      QUERY PLAN
-------------------------------------------------------
 BatchExchange { order: [], dist: Single }
   BatchHashJoin { type: Inner, predicate: t.x = i.x }
     BatchExchange { order: [], dist: HashShard(t.x) }
       BatchScan { table: t, columns: [x] }
     BatchScan { table: i, columns: [x] }
(5 rows)


select * from t join i using(x);
 x
---
 5
 3
(2 rows)

select * from t join i using(x);
 x
---
 4
(1 row)
```
---
Not fixed: Streaming MV on MV might have similar problem, because vnode mapping may change after scaling, so same ConsistentHashShard can also be different distribution. We may need to always insert exchange.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Review by fuyufjh — APPROVED** [review]
LGTM

**Comment by BowenXiao1999** [comment]
Why the two same query produce different results?

**Review by st1page — APPROVED** [review]
LGTM

**Comment by xxchan** [comment]
> Why the two same query produce different results?

lhs is hash partition, Rhs is consistent hash partition. When they meet each other, the result is random

**Pull request merged**
