### PR TITLE
feat(pgwire): report correct version on startup

### PR DESCRIPTION
**Pull request by BugenZhao**
Signed-off-by: Bugen Zhao <i@bugenzhao.com>

## What's changed and what's your intention?

As title. We will get the current package version at compile time using `vergen` crate, which provides much more flexibility if we want to extend it in the future. When pgwire accepts a new connection, it will return with the correct version field.

image

To avoid rebuild after committing, we do not put the git hash into the version for now.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)
- #793

### CODE REVIEW

**Review by skyzh — COMMENTED** [review]
This looks like to generate too many info on build time. https://crates.io/crates/vergen

I guess this will impact a lot on incremental build time. Why not simply:

```
let version = env!("CARGO_PKG_VERSION");
```

?

**Comment by skyzh** [comment]
I would prefer to have `risingwave_version` crate, and only `risingwave_cmd_all` on release mode will depend on it.

**Comment by neverchanje** [comment]
I'm just going to fix this problem and actually the server version here should not be the risingwave version. Since in some cases, the server version is used by the client to work around incompatibility issues. Suppose there's a feature not supported before postgres 8.1, the client can find other approach to achieve the same functionality. So basically, if we implement all the features based on postgres 9.5.0, we should not use the risingwave (e.g. 0.1.7) or the client will fail to connect as this pg version is too old to support.

**Comment by BugenZhao** [comment]
> I'm just going to fix this problem and actually the server version here should not be the risingwave version. Since in some cases, the server version is used by the client to work around incompatibility issues. Suppose there's a feature not supported before postgres 8.1, the client can find other approach to achieve the same functionality. So basically, if we implement all the features based on postgres 9.5.0, we should not use the risingwave (e.g. 0.1.7) or the client will fail to connect as this pg version is too old to support.

How does the client determine the version in general? Is it okay to put the risingwave version after the compatible postgresql version like "9.5.0-risingwave-0.1.7" or something?

**Comment by liurenjie1024** [comment]
How are we going to get the info as demonstrated in https://crates.io/crates/vergen? When I confront a bug, I want to know the git commit sha1 which produces this binary.

**Comment by BugenZhao** [comment]
> How are we going to get the info as demonstrated in https://crates.io/crates/vergen? When I confront a bug, I want to know the git commit sha1 which produces this binary.

I'm also considering putting the git hash into the version. However, this will let the whole project rebuild after each commit, which may reduce the development experience. 😢

**Comment by BugenZhao** [comment]
> This looks like to generate too many info on build time. https://crates.io/crates/vergen
> 
> I guess this will impact a lot on incremental build time. Why not simply:
> 
> ```
> let version = env!("CARGO_PKG_VERSION");
> ```
> 
> ?

Just in case we need to extend it with more detailed info...

**Comment by BugenZhao** [comment]
> I would prefer to have `risingwave_version` crate, and only `risingwave_cmd_all` on release mode will depend on it.

Reporting a meaningful version may also benefit developing or debugging. Let's listen to everyone's opinions. 🤣

**Comment by liurenjie1024** [comment]
> > How are we going to get the info as demonstrated in https://crates.io/crates/vergen? When I confront a bug, I want to know the git commit sha1 which produces this binary.
> 
> I'm also considering putting the git hash into the version. However, this will let the whole project rebuild after each commit, which may reduce the development experience. 😢

A single version may not be enough 😂

**Comment by neverchanje** [comment]
> How does the client determine the version in general?

@BugenZhao The server version can be known via the pgwire protocol, internally it will be encoded in the ParameterStatus message. I don't know if "9.5.0-risingwave-0.1.7" gonna work and I suggest using hard-coded "9.5.0" and encoding the system version later if we can ensure all the third-party tools are able to recognize versions in such format.

> At present there is a hard-wired set of parameters for which ParameterStatus will be generated: they are **server_version**, server_encoding, client_encoding, application_name, default_transaction_read_only, in_hot_standby, is_superuser, session_authorization, DateStyle, IntervalStyle, TimeZone, integer_datetimes, and 
https://www.postgresql.org/docs/current/protocol-flow.html#id-1.10.5.7.3

**Review by BowenXiao1999 — COMMENTED** [review]
The code LGTM

**Comment by BugenZhao** [comment]
I'd like to split this PR into two pieces of stuff. One for reporting a correct 

> > How does the client determine the version in general?
> 
> @BugenZhao The server version can be known via the pgwire protocol, internally it will be encoded in the ParameterStatus message. I don't know if "9.5.0-risingwave-0.1.7" gonna work and I suggest using hard-coded "9.5.0" and encoding the system version later if we can ensure all the third-party tools are able to recognize versions in such format.
> 
> > At present there is a hard-wired set of parameters for which ParameterStatus will be generated: they are **server_version**, server_encoding, client_encoding, application_name, default_transaction_read_only, in_hot_standby, is_superuser, session_authorization, DateStyle, IntervalStyle, TimeZone, integer_datetimes, and
> > https://www.postgresql.org/docs/current/protocol-flow.html#id-1.10.5.7.3
> 
> Btw Materialize uses 9.5.0. You can checkout their code: src/coord/src/session/vars.rs

According to [some doc](https://pgpedia.info/s/server_version.html), it seems the `server_version` is designed to be human-readable, and including additional information is allowed. Clients may check `server_version_num` integer instead to decide the postgresql version. However, we cannot ensure whether the client agrees with this in fact so this is just for our information. 🤣

**Comment by BugenZhao** [comment]
I think this PR should be split into two pieces of stuff. One for reporting a correct version with pgwire, another for generating a detailed enough version info for developers to debug.

**Comment by BugenZhao** [comment]
Some references on how libpq handles this.

https://github.com/postgres/postgres/blob/d22646922d66012705e0e2948cfb5b4a07092a29/src/interfaces/libpq/fe-exec.c#L1146-L1178

**Comment by BowenXiao1999** [comment]
A little unclear, can someone give me a conclusion?

Summarize the pros:
User may not care about the risingwave version, and they only care about Postgresql Version, so our server version may not be important and may cause confusion?  And the version may not be enough compared with git commit hash?

My understanding:
1. We should provide this info if the cost is not too much. For commit hash, we can try to find whether there is not-heavy approach to achieve in the future.
2. To solve https://github.com/risingwavelabs/risingwave-cloud/issues/1097, if we not going to solve it in, I think we can provide a specific SQL "select rw_version()". The cons is that this will not called by user if they do not care rw version, but cloud team can use this to get version.

**Comment by mikechesterwang** [comment]
🤔I think `select version()` is great
```
defaultdb=> select version();
                                       version
--------------------------------------------------------------------------------------
 CockroachDB CCL v22.1.11 (x86_64-pc-linux-gnu, built 2022/11/14 20:44:30, go1.17.11)
(1 row)
```

**Pull request closed without merging**
