### PR TITLE
refactor(metric): use more accurate backpressure metric

### PR DESCRIPTION
**Pull request by Sunt-ing**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
- Refactor backpressure metric to make it more accurate.
- Reasons:
  - Users may be confused when find always non-zero backpressure metric
  - It may potentially disturb some decisions made by control plane in the future
- Potential issue:
  - If a channel is blocked for a rather long duration, such as 1 min, then a long blocking time number, such as 1 min, will be reported to Prometheus, and so at some moment (and maybe some of its following moments) the average blocking time per second number would be very high. This can be solved by using tokio::time::timeout.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by Sunt-ing** [comment]
image
image

**Comment by fuyufjh** [comment]
> If a channel is blocked for a rather long duration, such as 1 min, then a long blocking time number, such as 1 min, will be reported to Prometheus

This sounds very misleading.

**Comment by fuyufjh** [comment]
> Users may be confused when find always non-zero backpressure metric

From my understanding, the metric actually shows time consumed to emit data into downstream queue in this second, so it would be expected if it's close to 0 instead of exactly 0.

**Comment by Sunt-ing** [comment]
Here we adopt the concept from [Flink backpressure monitoring](https://nightlies.apache.org/flink/flink-docs-master/docs/ops/monitoring/back_pressure/#back-pressure-status):
`backPressureTimeMsPerSecond`, time that subtask spent being back pressured.

So it's not `time consumed to emit data into downstream queue in this second`.
For example, in the [Flink backpressure monitoring](https://nightlies.apache.org/flink/flink-docs-master/docs/ops/monitoring/back_pressure/#back-pressure-status), we can find a table, which shows that this metric `backPressureTimeMsPerSecond` can be exactly 0:
image

**Comment by Sunt-ing** [comment]
> This sounds very misleading.

Indeed. Let me elaborate on it. In this backpressure metric implementation and all the previous implementations, we record elapsed time after the `send` operation is finished. So what if the `send` operator takes a long time (such as 1 hour) to finish? The number `1 hour` would be suddenly added to the metric `backPressureTimePerSecond` after the `send` operation is finished. And in the Grafana, we can observe a sharp increase (3600 s / 15s) = 24000% backpressure percentage, where 15s is the `rate_interval`.
However, we didn't observe such behavior yet.

Am I clear now?

**Comment by Sunt-ing** [comment]
@fuyufjh have I answered all your questions?

**Comment by fuyufjh** [comment]
Yes, thanks! I agree that "exactly 0" is better according to the definition of `backPressureTimeMsPerSecond`, but 


>> If a channel is blocked for a rather long duration, such as 1 min, then a long blocking time number, such as 1 min, will be reported to Prometheus
>
> This sounds very misleading.

For this part, developers and users won't care about your implementation. Instead, they think it a bug.

**Comment by Sunt-ing** [comment]
> they think it a bug

Yes, this is a bug. I'm thinking about whether to fix it right now or later when we actually find such a bug.

**Comment by Sunt-ing** [comment]
A demo implementation:
```rust
use std::time::Duration;

#[tokio::main]
async fn main() {
    let (tx, rx) = tokio::sync::mpsc::channel(1);
    tx.send(233).await.unwrap();
    let mut blocking_time = 0;
    while let Err(_) = tokio::time::timeout(Duration::from_secs(1), tx.send(233)).await {
        blocking_time += 1;
        println!("Blocking time: {}", blocking_time);
    }
    println!("Hello, world!");
}


```

**Comment by Sunt-ing** [comment]
After changing, the code snippet may be as follows. I'm not sure whether this complexity is acceptable.
```rust

    async fn send(&mut self, message: Message) -> Result<()> {
        // if the buffer is full when sending, the sender is backpressured
        if self.ch.capacity() == 0 {
            let start_time = minstant::Instant::now();
            let mut timeout_times = 0;
            // the default pull time of Prometheus is 15s, so we set timeout to 10s
            while let Err(_) = tokio::time::timeout(
                std::time::Duration::from_secs(10),
                self.ch.send(message.clone()),
            )
            .await
            .map_err(|_| internal_error("failed to send"))?
            {
                self.metrics
                    .actor_output_buffer_blocking_duration_ns
                    .with_label_values(&[&self.up_id_str])
                    .inc_by(10_000_000_000);
                timeout_times += 1;
            }
            self.metrics
                .actor_output_buffer_blocking_duration_ns
                .with_label_values(&[&self.up_id_str])
                .inc_by(start_time.elapsed().as_nanos() as u64 - timeout_times * 10_000_000_000);
        } else {
            self.ch
                .send(message)
                .await
                .map_err(|_| internal_error("failed to send"))?;
        }
        Ok(())
    }
```

**Comment by Sunt-ing** [comment]
@fuyufjh I fixed this bug, but in this case, we may need to clone the `message` every time we want to send it. I'm not sure whether this is acceptable. If not, I will revert this bug fix.

**Comment by Sunt-ing** [comment]
@fuyufjh PTAL

**Pull request closed without merging**
