### PR TITLE
refactor: make `PlanNode Trait` like `ToBatch` return `Result` 

### LINKED ISSUE #2374: PlanNode::ToBatch and ToStream should return Result
In most cases, we will not implement the same operator in two engines in the same PR, so it's a strong requirement that not panic while a part of an operator is not implemented.

### PR DESCRIPTION
**Pull request by likzn**
## What's changed and what's your intention?

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
As issue #2374  say, make `return` as `Result` can make us do more thing.
- How does this PR work? Need a brief introduction for the changed logic (optional)
Refactor some trait in `src/frontend/src/optimizer/plan_node/convert.rs` like `ToBatch`,`ToStream`.Make them `return` as `Result`
And update with them implemention.

- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)
close #2374

### CODE REVIEW

**Comment by likzn** [comment]
@TennyZhuang  PTAL if free. And I had run e2e test loacl. It passed.

**Comment by TennyZhuang** [comment]
Thanks! Will take a look today

**Review by TennyZhuang — APPROVED** [review]
LGTM

**Comment by TennyZhuang** [comment]
CI is running: https://github.com/singularity-data/risingwave/actions/runs/2298833293

**Pull request merged**
