### PR TITLE
fix(local_version): fix deadlock bug

### PR DESCRIPTION
**Pull request by Little-Wallace**
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

https://github.com/singularity-data/risingwave/pull/3620 and https://github.com/singularity-data/risingwave/pull/3651 port a upgradable RWLock for local_version and it would cause deadlock bug in some case, see details in https://github.com/singularity-data/risingwave/issues/4354.

parking_lot::RWMutex acquires that it can not be access twice in one thread. If some thread hold one read-lock and it sends some message by a tokio::Sender, it may execute another function in the same thread and it would cause deadlock. This may be why we could only see one thread stack in the  log.

But I could still not tell which code we use RWLock incorrectly, I just think we may be able to solve this problem by rollback to the old code. And we shall keep the issue opening because this PR may not solve the problem.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Review by fuyufjh — APPROVED** [review]
LGTM as soon as it can pass CI

**Review by Li0k — APPROVED** [review]
LGTM! thanks

**Review by hzxa21 — APPROVED** [review]

**Comment by fuyufjh** [comment]
I have checked the checkboxes

**Review by MrCroxx — APPROVED** [review]

**Review by wenym1 — APPROVED** [review]

**Comment by BugenZhao** [comment]
> If some thread hold one read-lock and it sends some message by a tokio::Sender.

Does the read guard go across the await point in this case?

**Pull request merged**
