### PR TITLE
fix(meta): Stale SST Metrics without Alive Compactors #4380

### PR DESCRIPTION
**Pull request by KivenChen**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This PR solves the issue of stale metrics when no compactor present.

- add trigger for SST metrics update in `commit_epoch`
- refactor `trigger_sst_metrics` to make `compact_status optional`
- add `num_levels` to `HummockVersionExt` to avoid confusion

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
#4380

### CODE REVIEW

**Comment by KivenChen** [comment]
PTAL @hzxa21 @wenym1

**Review by hzxa21 — APPROVED** [review]

**Comment by hzxa21** [comment]
Can you also try this PR locally to verify the metric is correct in grafana dashboard before merging?

**Comment by KivenChen** [comment]
> Can you also try this PR locally to verify the metric is correct in grafana dashboard before merging?

To verify this metric, I started a full cluster and ran a newly-developed `tach-bench` on Kafka sources and MVs. Before #4571, the compactor was manually shut down and the metrics was cut out.

image

After #4571, the `SST count` and `SST size` metrics were updated even if the compactor was down (In comparison, metrics strongly relevant to compactor tasks were down as expected)

image

This PR proved to work some how

**Comment by KivenChen** [comment]
I also observed that the object storage's `read-xx` metric dies with the compactor while some of the others do not. Should we start an new issue for it? @hzxa21 

image

**Comment by hzxa21** [comment]
> I also observed that the object storage's `read-xx` metric dies with the compactor while some of the others do not. Should we start an new issue for it? @hzxa21
> 
> image

I think that is acceptable because even though we show emit these metrics, they are always 0 if the compactor dies.

**Pull request merged**
