### PR TITLE
feat(build): link openssl statically

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

## What's changed and what's your intention?

Statically link openssl.

Need to test if works with s3.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

close https://github.com/singularity-data/risingwave/issues/2973

### CODE REVIEW

**Comment by skyzh** [comment]
Basically, enabling statically linked openssl is as easy as

```
openssl = { version = "0.10", features = ["vendored"] }
```

However, this change involves too many other changes, like enabling cert discovery by ourselves. So I'd close this and see if we really need statically link openssl in the future. Indeed, we can use rustls instead.

**Comment by skyzh** [comment]
```
~/risingwave$ ldd target/debug/risingwave
        linux-vdso.so.1 (0x00007fff97fae000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fea8225c000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fea8223c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fea82155000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fea81f2d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fea8c8ef000)
```

**Review by neverchanje — APPROVED** [review]

**Comment by skyzh** [comment]
Tested and works with s3. However, unit test OOM. We should have a flag to enable / disable statically linked openssl...

**Comment by skyzh** [comment]
There're still bugs with cargo-hakari that prevents setting the feature flag. Need to report to upstream 😇

**Comment by skyzh** [comment]
Also a bug with rustc. It seems that compile RisingWave 1. with static-link 2. and then without it will cause linker to panic. Anyway, `cargo clean` always works.

**Pull request merged**
