### PR TITLE
feat(streaming): correctly implement LookupUnionExecutor

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

## What's changed and what's your intention?

Basically, what we are doing here is to forward data one input by one input. To avoid blocking upstream channels, we will need to store all data into a local buffer, which caused this part somehow not easy to read. Not sure how to write this in a better way. cc @wangrunji0408 may take a look and shed some light.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)

close https://github.com/singularity-data/risingwave/issues/2141

### CODE REVIEW

**Comment by wangrunji0408** [comment]
Can we spawn new futures to buffer upstreams? Then the union executor could await these futures sequentially.

**Comment by skyzh** [comment]
> Can we spawn new futures to buffer upstreams? Then the union executor could await these futures sequentially.

Nope. Executors need back pressure. If union executors cannot send its data to downstream, it should stop receiving data from upstream.

Also we assume one actor only creates one thread. There should not be un-managed spawned future in actors and executors.

**Comment by wangrunji0408** [comment]
I have a solution that might look better. See 77c40a25.

The key points are:
- Use bounded channels as buffers with backpressure.
- To avoid blocking upstream, create a future for each input to poll the stream and forward its output to the channel. The executor can then await the channels one by one, which greatly simplifies the code.
- Although spawning futures is not allowed, to ensure they are being polled, we can `select` them on all `.await` points.

**Comment by skyzh** [comment]
That's cool! I'll cherry-pick that commit to my branch... tomorrow for sure 🤣

**Comment by wangrunji0408** [comment]
> Also we assume one actor only creates one thread. There should not be un-managed spawned future in actors and executors.

And I still think spawning futures should be allowed. It wouldn't create new threads, just create a new task.
To avoid dangling futures, we can use [smol-style task handle](https://docs.rs/smol/latest/smol/struct.Task.html), which will cancel the task on drop, instead of detaching it.
Once all task handles are properly stored somewhere, we can make sure that all tasks are under the control.

In this case, I don't think the executor itself should care whether the upstreams would be blocked or not. If an upstream is not allowed to be blocked by downstream, we should spawn a future to poll it and connect futures using a channel as a buffer. Therefore, no matter what the downstream executor is, the upstream will never be blocked.

**Comment by yuhao-su** [comment]
LGTM

**Pull request merged**
