### PR TITLE
chore(risedev): update grafana version

### PR DESCRIPTION
**Pull request by wcy-fdu**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

Update grafana version to `9.0.0`, see [What's new in grafana 9.0](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-0/).

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by skyzh** [comment]
Better to follow `etcd.toml` and see how we can force upgrade existing users' Grafana to latest version :)

**Comment by wcy-fdu** [comment]
> Better to follow `etcd.toml` and see how we can force upgrade existing users' Grafana to latest version :)

It seems that `etcd.toml` does not support this logic, it only judge the version of the system? cc @TennyZhuang

**Comment by skyzh** [comment]
Oh, let me see, I might have remembered it wrong.

**Review by skyzh — APPROVED** [review]

**Comment by skyzh** [comment]
I'll do some test on my local environment. DNM for now.

**Pull request merged**
