### PR TITLE
refactor: rename DebugExecutor to WrapperExecutor

### PR DESCRIPTION
**Pull request by fuyufjh**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title. The name "debug" often shows in the stack trace and looks misleading - it not only works in debug build. 

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

None

## Refer to a related PR or issue link (optional)
None

### CODE REVIEW

**Review by BugenZhao — APPROVED** [review]

**Comment by neverchanje** [comment]
"Wrap" sounds more confusing...  ExecutorWrapper, IntrumentedExecutor, WrappedExecutor, etc

**Comment by fuyufjh** [comment]
> "Wrap" sounds more confusing...  ExecutorWrapper, IntrumentedExecutor, WrappedExecutor, etc.
> 
> (Nevermind, I dont have better name either.

How about WrappingExecutor? Would it be better?

**Comment by BugenZhao** [comment]
Or simply `CheckExecutor`? All LGTM. 🤔

**Comment by fuyufjh** [comment]
Renamed to "WrapperExecutor", which is the best name I could think of.

**Comment by fuyufjh** [comment]
@mergifyio requeue

**Pull request merged**
