### PR TITLE
refactor(storage): use iter instead of scan in CellBasedTableRowIter

### PR DESCRIPTION
**Pull request by lmatz**
## What's changed and what's your intention?
As the title suggests, we should use iter in most cases unless we know for sure that we need to scan a number of kv pairs all at once.

## Refer to a related PR or issue link (optional)
#2221

### CODE REVIEW

**Comment by skyzh** [comment]
I'd prefer to get this merged only when

> Currently, the vacuumer will only delete files < min pinned epoch. But if we optimize it to delete all files that aren't referenced, it's also okay to store the iter inside batch scan.

... this optimization is done. Otherwise, space amplification would be rather high.

**Comment by lmatz** [comment]
> I'd prefer to get this merged only when
> 
> > Currently, the vacuumer will only delete files < min pinned epoch. But if we optimize it to delete all files that aren't referenced, it's also okay to store the iter inside batch scan.
> 
> ... this optimization is done. Otherwise, space amplification would be rather high.

Sure, let's hold this for a second. Is anyone working on this now?

**Comment by skyzh** [comment]
Not yet 🤣

**Comment by lmatz** [comment]
The issue that this pr tries to deal with will be solved in PR #2339. Close now.

**Pull request closed without merging**
