### PR TITLE
chore: Ignore commits in the blame view

### PR DESCRIPTION
**Pull request by xxchan**
## What's changed and what's your intention?
as title
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

### On GitHub

before 
image

after
image

### Enable Locally
```bash
git config blame.ignoreRevsFile .git-blame-ignore-revs
```

## Checklist

- ~~[ ] I have written necessary docs and comments~~
- ~~[ ] I have added necessary unit tests and integration tests~~
- ~~[ ] All checks passed in `./risedev check` (or alias, `./risedev c`)~~

### CODE REVIEW

**Comment by skyzh** [comment]
* GitHub web page doesn't support this 🤣
* We have a lot of other refactor commits, would you please also help add them in? (like add license, move rust/ to src, etc.)

**Comment by xxchan** [comment]
> GitHub web page doesn't support this 🤣

It is supported. See the screenshot. 🤔

> We have a lot of other refactor commits, would you please also help add them in? (like add license, move rust/ to src, etc.)

OK

**Comment by skyzh** [comment]
That's cool, so GitHub has upgraded 🤣

**Comment by xxchan** [comment]
Just searched "rename" and randomly added some. 🤪 Let's add more when they are encountered! 🐶

Btw, I think adding license doesn't need to be ignored since it does not override other blames?

**Comment by skyzh** [comment]
> Btw, I think adding license doesn't need to be ignored since it does not override other blames?

Agree!

**Review by skyzh — APPROVED** [review]

**Pull request merged**
