### PR TITLE
refactor(proto): clean up unused methods in risingwave_pb

### PR DESCRIPTION
**Pull request by TennyZhuang**
Signed-off-by: TennyZhuang <zty0826@gmail.com>

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

1. Remove unused methods
2. Move some methods to common. 

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

### CODE REVIEW

**Review by neverchanje — APPROVED** [review]
lgtm

**Review by skyzh — APPROVED** [review]
LGTM but I guess people would still use those function wrongly. An autocompletion will bring those functions into namespace. If they are only used in tests, name those functions like test_new_struct.

**Review by yezizp2012 — APPROVED** [review]

**Comment by TennyZhuang** [comment]
> LGTM but I guess people would still use those function wrongly. An autocompletion will bring those functions into namespace. If they are only used in tests, name those functions like test_new_struct.

ntfs, there are many other methods.

**Comment by skyzh** [comment]
> > LGTM but I guess people would still use those function wrongly. An autocompletion will bring those functions into namespace. If they are only used in tests, name those functions like test_new_struct.
> 
> ntfs, there are many other methods.

Then at least add docstring for those functions, `/// only used for tests`.

**Pull request merged**
