### PR TITLE
test: add nexmark e2e

### PR DESCRIPTION
**Pull request by neverchanje**
## What's changed and what's your intention?

The testing data was generated by https://github.com/singularity-data/risingwave/pull/540, rather than the java version nexmark. So I only include dozens of records. When eventually our nexmark is stable, I will update the dataset. For example, the events currently in the testdata happened too close: 

```
1000    1001    453927.360  2015-07-15 00:00:00.001
1000    1007     11490.740  2015-07-15 00:00:00.001
1012    1003     17496.252  2015-07-15 00:00:00.001
1000    1001  39654430.240  2015-07-15 00:00:00.001
1000    1010       213.380  2015-07-15 00:00:00.001
1007    1001       219.736  2015-07-15 00:00:00.002
1012    1001  64544054.080  2015-07-15 00:00:00.002
1009    1001    190643.680  2015-07-15 00:00:00.002
1003    1001  80837009.952  2015-07-15 00:00:00.002
1000    1002       292.376  2015-07-15 00:00:00.002
1000    1004      2132.892  2015-07-15 00:00:00.003
1011    1001      4771.540  2015-07-15 00:00:00.003
1000    1001  12696452.316  2015-07-15 00:00:00.003
1001    1001     77120.980  2015-07-15 00:00:00.003
1000    1001  26038438.152  2015-07-15 00:00:00.003
1000    1001   1753269.004  2015-07-15 00:00:00.004
1000    1001    515363.548  2015-07-15 00:00:00.004
1010    1001       193.404  2015-07-15 00:00:00.004
1006    1001  19666916.800  2015-07-15 00:00:00.004
1012    1001    154414.480  2015-07-15 00:00:00.004
1010    1002      1899.536  2015-07-15 00:00:00.005
```

In order to test window functions like HOP and TUMBLE, the timestamps should be in a wide time period. 

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
Looks cool! The only concern is that it seems that `risingwave_expr` is added back as the dependency of `risingwave_source`, which will cause compilation of `risingwave_source` depending on `risingwave_expr`. Do we really need to re-use the scalar function implementation in `risingwave_expr`?

**Comment by neverchanje** [comment]
I think we always need to prevent repeating the code. If the dependency is really a trouble, we can extract the particular code to the common crate. Anyway, source will heavily rely on str parsing. If you agree I will do that in next pr.

**Review by KeXiangWang — APPROVED** [review]
LGTM

**Comment by skyzh** [comment]
> I think we always need to prevent repeating the code. If the dependency is really trouble, we can extract the particular code to the common crate. Anyway, source will heavily rely on str parsing. If you agree I will do that in the next pr. @skyzh

Then I'd be okay to move them to risingwave_expr or risingwave_common. 🤪

**Pull request merged**
