### PR TITLE
feat(test): parallelize sqlsmith test

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

## What's changed and what's your intention?

As title

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

close https://github.com/singularity-data/risingwave/issues/3349

### CODE REVIEW

**Review by neverchanje — APPROVED** [review]
Nice job!

**Comment by skyzh** [comment]
@Mergify unqueue

**Comment by skyzh** [comment]
@neverchanje do we expect the test cases to be different on each run, or assign a seed in advance? Before this PR we are using completely random data on each run, and now we are specifying seeds.

**Comment by skyzh** [comment]
@Mergify requeue

**Comment by TennyZhuang** [comment]
I'd prefer using a determined seed in the PR CI, and use a randomized seed in a daily CI.

**Comment by TennyZhuang** [comment]
> @mergify requeue

Do you want to unqueue?

**Comment by TennyZhuang** [comment]
The principle is that the PR author should not pay effort into the bugs not introduced by him.

**Pull request merged**
