### PR TITLE
binder: support string interval

### LINKED ISSUE #3003: bug: `interval` doesn't work as expected
**Describe the bug**

```
dev=> select interval '5 days';
ERROR:  Invalid input syntax: Invalid interval 5 days.
dev=> select interval '1 day';
ERROR:  Invalid input syntax: Invalid interval 1 day.
dev=> select interval '1 hour';
ERROR:  Invalid input syntax: Invalid interval 1 hour.
dev=> select interval '1 second';
ERROR:  Invalid input syntax: Invalid interval 1 second.
```

**To Reproduce**

See above.

**Expected behavior**

Tested on PG:

```
dev=# select interval '5 days';
 interval
----------
 5 days
(1 row)

dev=# select interval '1 day';
 interval
----------
 1 day
(1 row)

dev=# select interval '1 hour';
 interval
----------
 01:00:00
(1 row)

dev=# select interval '1 second';
 interval
----------
 00:00:01
(1 row)

```

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by likzn**
## What's changed and what's your intention?

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
Add a func to parse the argument of interval with specific syntax. Like @xiangjinwu point out in issue.
But now only support like `select interval '5 days'; `

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
close #3003

### CODE REVIEW

**Review by xiangjinwu — COMMENTED** [review]
lgtm. Could you add some unit tests as well?

**Review by xiangjinwu — APPROVED** [review]
Thanks for the contribution.

**Comment by bernscode** [comment]
@likzn @xiangjinwu Is this update intentionally excluding 'week' as a supported interval unit?

**Comment by xiangjinwu** [comment]
> @likzn @xiangjinwu Is this update intentionally excluding 'week' as a supported interval unit?

Sort of. We just supported the basic units (year, month, day, hour, minute, second) first, and other units (millennium, century, decade, week, millisecond, microsecond) can be supported later when needed. It is true that we are far from the [complete](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT) support.

**Pull request merged**
