### PR TITLE
WIP: mutate multiple dispatchers instead of dispatchers' outputs

### PR DESCRIPTION
**Pull request by xxchan**
## Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional) 

close https://github.com/singularity-data/risingwave/issues/2272

### CODE REVIEW

**Review by skyzh — COMMENTED** [review]
Generally on the right direction, good work! Then the next problem is how to store the correspondence between MV actors and their dispatcher IDs (which will be used in create MV commands...)

**Comment by skyzh** [comment]
Linked to a new issue -> https://github.com/singularity-data/risingwave/issues/2272

**Comment by skyzh** [comment]
any updates? 🤪

**Comment by BugenZhao** [comment]
I'd like to continue working on this. 🤣

**Pull request closed without merging**
