### PR TITLE
refactor(frontend): remove calls to `gen_batch_query_plan` 

### LINKED ISSUE #2127: refactor: remove calls to `gen_batch_query_plan`
Remove all calls to `gen_batch_query_plan()` and use `gen_dist_batch_query_plan()` instead.

https://github.com/singularity-data/risingwave/blob/3b06cfdd4a4a370e65e1933ab7e03a8053575505/src/frontend/src/optimizer/mod.rs#L158-L181

### PR DESCRIPTION
**Pull request by fuyufjh**
## What's changed and what's your intention?

As title

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)

closes #2127

### CODE REVIEW

**Review by liurenjie1024 — COMMENTED** [review]
I would keep this `gen_batch_query_plan` because it seems useful for local execution mode. But we can update the comments.

**Comment by liurenjie1024** [comment]
> lgtm, we support local exchange bypassing the network. So even in local execution mode (actually we don't have this mode), theoretically, the distributed plan costs nearly no more than single-node plan.

The problem is local execution mode's plan should be different from distributed mode's plan. We should not introduce unnecessary exchange.

**Comment by fuyufjh** [comment]
> I would keep this gen_batch_query_plan because it seems useful for local execution mode. But we can update the comments.

Whether to add exchange is totally **determined** by the non-distributed plan. 

For example, if the optimizer generates:

```
                 HashJoin (t1.x == t2.x)
               /     \
 t1 (distributed by k1)   t2  (distributed by k2)
```

Then you have no choice but to add an Exchange on the TableScans

For another example, if the optimizer generates:

```
               LookupJoin (t1.x == t2.x)
               /     \
      t1 (k1=1)   t2  (distributed by x)
```

Then you CANNOT add an Exchange in it.

**Comment by liurenjie1024** [comment]
> ```
>                  HashJoin (t1.x == t2.x)
>                /     \
>  t1 (distributed by k1)   t2  (distributed by k2)
> ```

For this case, in local distribution mode, we need a `GenericExchange` to gather `TableScan` node, rather add an `GenericExchange` over `TableScan` to sastisfy `Hash` distribution.

**Comment by fuyufjh** [comment]
> For this case, in local distribution mode, we need a GenericExchange to gather TableScan node, rather add an GenericExchange over TableScan to sastisfy Hash distribution.

So it's an MPP TableScan + single-node HashJoin... It's almost infeasible 😇

**Comment by liurenjie1024** [comment]
> 

Yes, what I want to say is that in local execution mode, the generated plan should be different from mpp mode. And that's why I want to keep it as an entry point for customized plan generation.

**Comment by fuyufjh** [comment]
> Yes, what I want to say is that in local execution mode, the generated plan should be different from mpp mode. And that's why I want to keep it as an entry point for customized plan generation.

At least the step of adding Exchange should be same

**Comment by liurenjie1024** [comment]
> 

No, it's not. In mpp mode, the exchange is hash shuffle while in local execution mode it's simple gather.

**Comment by fuyufjh** [comment]
> No, it's not. In mpp mode, the exchange is hash shuffle while in local execution mode it's simple gather.

I have explained this before. Don't do this 😇😇😇

**Comment by liurenjie1024** [comment]
I got what you mean.  Another function name maybe better solution.

**Review by liurenjie1024 — APPROVED** [review]
LGTM

**Comment by fuyufjh** [comment]
For another example --- `TopN` (same for `HashAgg`)

The optimizer will always ensure `TopN` as singleton:

```
   TopN
    |
Exchange (gather)
    |
 TableScan
```

That's good. You can run the `TopN` in local execution mode, maybe on the frontend node. This is reasonable because the optimizer knows that TopN won't consume too much memory, so the optimizer is happy to let it be singleton.

On the other hand, for `HashJoin` or something else, the optimizer knows: Oh, the data on it must be the same scale of TableScan; since TableScan is distributed, HashJoin must also be distributed, but with another distribution key. Therefore, it's really bad to force the HashJoin to be singleton, as you suggested in that example.

**Pull request merged**
