### PR TITLE
feat(streaming): [DO NOT MERGE]temporary solution for monotonic epoch using quanta::Clock

### PR DESCRIPTION
**Pull request by yezizp2012**
## What's changed and what's your intention?

A temporary solution for monotonic epoch using [quanta::Clock](https://docs.rs/quanta/latest/quanta/struct.Clock.html). ~~To support concurrent checkpoint (two epoch may be generate in same millisecond),  here we use nano instead.~~

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)
https://github.com/singularity-data/risingwave/issues/2011

### CODE REVIEW

**Comment by BugenZhao** [comment]
> To support concurrent checkpoint (two epoch may be generate in same millisecond), here we use nano instead.

Seems u64 is far from enough for nanoseconds? Besides, why we'll issue checkpoints so fast?

**Comment by yezizp2012** [comment]
> > To support concurrent checkpoint (two epoch may be generate in same millisecond), here we use nano instead.
> 
> Seems u64 is far from enough for nanoseconds? Besides, why we'll issue checkpoints so fast?

`u64` is enough for nanoseconds if I calculate correctly, (2^64-1)/365/24/3600/1000000000 = 584.9 year. Actually this may not work for normal checkpoint but other commands. This situation met by @xxhZs when work on concurrent checkpoint in https://github.com/singularity-data/risingwave/pull/2184. I agree that we should not issue checkpoint(generate epoch) that fast(each checkpoint is accompanied by the flush of all executors). Maybe we should also control the frequency and trigger conditions of concurrent checkpoint, to ensure generate epoch in same milliseconds not happen. Anyway, still need some discussion on this.

**Comment by skyzh** [comment]
By the way, I think it's also better to print a warning in debug mode if we found that two epochs are too close. For most of the time, I guess generating epochs too frequently is related to a bug.

**Comment by skyzh** [comment]
> Maybe we should also control the frequency and trigger conditions of concurrent checkpoint, to ensure generate epoch in same milliseconds not happen.

I think so. I haven't taken a deep look into the concurrent checkpoint PR, but I believe that in all circumstances the epoch generation should not be within milliseconds.

**Comment by yezizp2012** [comment]
`quanta::Clock` only guaranteed to return a monotonically increasing value between calls to the same `Clock` instance. After some test locally, reboot the host machine the value will goes backwards to some unknown starting point. This is not an available library in the epoch scenario. It only works for scenario like metrics.

**Pull request closed without merging**
