### PR TITLE
refactor(storage): move hummock tests to a new crate to break crate cyclic dependency

### LINKED ISSUE #3766: resolve cyclic dependency between `meta` and `storage`
This might cause some proc macros to fail to be resolved.

```
[ERROR project_model::workspace] cyclic deps: risingwave_storage(CrateId(389)) -> risingwave_meta(CrateId(372)), alternative path: risingwave_meta(CrateId(372)) -> risingwave_connector(CrateId(364)) -> risingwave_storage(CrateId(389))
thread 'MacroExpander' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/handle.rs:22:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: proc_macro_srv::abis::abi_1_63::proc_macro::bridge::client::HandleStore<S>::new
   5: proc_macro_srv::abis::abi_1_63::proc_macro::bridge::server::run_server
   6: proc_macro_srv::abis::abi_1_63::Abi::expand
   7: proc_macro_srv::dylib::Expander::expand
   8: proc_macro_srv::cli::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

https://github.com/singularity-data/risingwave/blob/3d8f5fa8a6b3fcd0a93482cc121746f0c0d478cd/src/storage/Cargo.toml#L78-L80

https://github.com/singularity-data/risingwave/blob/3d8f5fa8a6b3fcd0a93482cc121746f0c0d478cd/src/meta/Cargo.toml#L38

Should we extract a `connector_sdk` crate for meta to depend on? 🤣

### PR DESCRIPTION
**Pull request by wenym1**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Some hummock unit tests depend on the meta crate, while some dependencies of meta depend on storage, which causes cyclic dependency. In this PR, we move the hummock unit tests that depend on meta crate to a new crate so that there will not be any cyclic dependency.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
close #3766

### CODE REVIEW

**Comment by TennyZhuang** [comment]
Please resolve the conflicts

**Comment by wenym1** [comment]
@skyzh Could you test whether the cyclic dependency is broken?

**Comment by TennyZhuang** [comment]
Seems work for me, great!

**Review by hzxa21 — APPROVED** [review]

**Review by skyzh — APPROVED** [review]
no more cycles! Good work!

Please add workspace-hack to the new crate. Also it would be better if you can wrap everything inside `risingwave_hummock_test` in `#[cfg(test)]`.

**Comment by BugenZhao** [comment]
> Please add workspace-hack to the new crate. Also it would be better if you can wrap everything inside `risingwave_hummock_test` in `#[cfg(test)]`.

Since this crate is not dependent on `risingwave_cmd`, will it only be compiled accidentally with workspace-level `cargo build`?

**Review by wcy-fdu — APPROVED** [review]

**Comment by skyzh** [comment]
> > Please add workspace-hack to the new crate. Also it would be better if you can wrap everything inside `risingwave_hummock_test` in `#[cfg(test)]`.
> 
> Since `risingwave_cmd` is not dependent on this crate, so it will only be compiled accidentally with workspace-level `cargo build`?

Got it.

**Pull request merged**
