### PR TITLE
chore(ci): use one session for each file in serial mode e2e tests

### PR DESCRIPTION
**Pull request by xxchan**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
To reflect the change of https://github.com/risinglightdb/sqllogictest-rs/pull/86

### CODE REVIEW

**Review by skyzh — APPROVED** [review]

**Comment by BugenZhao** [comment]
So the distributed batch e2e becomes completely local mode now. How about adding a new step of distributed mode?

**Comment by xxchan** [comment]
> So the "distributed" batch e2e becomes completely local mode now. How about adding a new step of distributed mode?

What do you mean? We have `distribution_mode.slt`? Didn't get it.

**Comment by xxchan** [comment]
Oh you mean `tpch.slt`?

**Comment by BugenZhao** [comment]
> > So the "distributed" batch e2e becomes completely local mode now. How about adding a new step of distributed mode?
> 
> 
> 
> What do you mean? We have `distribution_mode.slt`? Didn't get it. 

https://github.com/singularity-data/risingwave/pull/4789

**Comment by xxchan** [comment]
Oh, the script `run-e2e-test.sh` has a section `batch distributed` 🤪

**Comment by xxchan** [comment]
I just updated the section description. Not sure whether to add a `tpch_distributed.slt`🤪 cc @liurenjie1024

**Comment by liurenjie1024** [comment]
I don't think we need a tpch_distributed, but add set distributed mode in tpch file.

**Comment by BugenZhao** [comment]
> I don't think we need a tpch_distributed, but add set distributed mode in tpch file.

How about running all cases in both modes? 🤔

**Comment by liurenjie1024** [comment]
> How about running all cases in both modes? 🤔

Generally I'm ok with this, the only concern is that local mode maybe too slow for tpch.

**Comment by liurenjie1024** [comment]
IIUC, if a file included in slt file, for example:
```
include a.slt.part
include b.slt.part
```
 a and b are still using same session, right? cc @xxchan @BugenZhao

**Pull request merged**
