### PR TITLE
refactor(batch): Use futures-async-stream to implement StreamScan executor

### PR DESCRIPTION
**Pull request by D2Lark**
Signed-off-by: d2lark <lichengamoy@gmail.com>

##  Implement StreamScanExecutor  using Executor2 trait

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)
close https://github.com/singularity-data/risingwave/issues/1944

### CODE REVIEW

**Review by TennyZhuang — APPROVED** [review]
LGTM

**Comment by TennyZhuang** [comment]
https://github.com/singularity-data/risingwave/actions/runs/2243726092

**Comment by TennyZhuang** [comment]
CI failed due to an unstable test and someone is working on fix it, please wait a moment.

**Review by liurenjie1024 — APPROVED** [review]

**Comment by TennyZhuang** [comment]
CI: https://github.com/singularity-data/risingwave/actions/runs/2243765265

**Comment by D2Lark** [comment]
> CI: https://github.com/singularity-data/risingwave/actions/runs/2244511049

my bad？

**Comment by TennyZhuang** [comment]
> > CI: https://github.com/singularity-data/risingwave/actions/runs/2244511049
> 
> my bad？

seems not, I will investigate on it

**Comment by TennyZhuang** [comment]
(rerun) CI is running: https://github.com/singularity-data/risingwave/actions/runs/2244749127

**Comment by TennyZhuang** [comment]
Thanks!

**Pull request merged**
