### PR TITLE
feat(meta): introduce table-granularity vnode hash mapping

### PR DESCRIPTION
**Pull request by xx01cyx**
### Summarize your change

- Introduce `HashMappingStrategy` for each relational state table. This allows each relational state table to have its own vnode hash mapping (hash ring in consistent hash). In this way, **different MVs can have different parallelism requirements and data distributions**.
- Since hash mapping is really space-consuming (2048 * 4 or 65536 * 4 bytes per hash mapping), only one hash mapping is stored for each hash mapping strategy, instead of one per table. After introducing custom strategies, there will still be many tables using the default strategy. So this could save much space and reduce the amount of meta data to maintain.

### Describe any limitations of the current code

- What should be put in `HashMappingStrategy` still needs design.
- All the data are volatile in memory now. Hummock API in meta **requires struct to be defined in proto**. That makes it really hard to persist a struct like 

   ```rust
   pub enum HashMappingStrategy {
       Default,
       Custom(TableId),
   }  
   ```
   which is what I plan to use as the key of hash mapping. I'm trying to figure out a workaround for this.

## Checklist

- [x] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests

### CODE REVIEW

**Comment by fuyufjh** [comment]
IIUC, to get the hash mapping of a table, one must lookup `operator_strategies` by table_id to get the `HashMappingStrategy`, and then, lookup `mapping_infos` to get the actual `HashMappingInfo`, right?

Hmmm, why not just use a 1-layer lookup, i.e. table_id to `HashMappingInfo` directly?

**Comment by xx01cyx** [comment]
> IIUC, to get the hash mapping of a table, one must lookup `operator_strategies` by table_id to get the `HashMappingStrategy`, and then, lookup `mapping_infos` to get the actual `HashMappingInfo`, right?
> 
> Hmmm, why not just use a 1-layer lookup, i.e. table_id to `HashMappingInfo` directly?

Yes. IMO a number of tables will still use the default strategy. So it's more portable to store `HashMappingInfo` according to strategy, instead of table. This **avoids altering too much data when a node joins or leaves the cluster**. 

Besides, this also **allows tables to share one custom strategy**.

**Comment by fuyufjh** [comment]
> Yes. IMO a number of tables will still use the default strategy. So it's more portable to store `HashMappingInfo` according to strategy, instead of table. This **avoids altering too much data when a node joins or leaves the cluster**.
> 
> Besides, this also **allows tables to share one custom strategy**.

But the strategy is hard-coded in an `enum`, and it's not easy to make it configurable. That is, if the storage module or user decides to create a new 'strategy', how can they add this strategy into `enum HashMappingStrategy`?

Another reason is: imagine that we are going to support adding compute nodes on the fly, in this case, the MVs created before adding new node is running on N nodes, and the MVs created after adding new node will run on N+1 nodes. Here they use different `HashMappingInfo`, but this not caused by difference of strategy - they should share the same strategy to ensure they take use of all nodes after a cluster reboot.

**Comment by hzxa21** [comment]
> > IIUC, to get the hash mapping of a table, one must lookup `operator_strategies` by table_id to get the `HashMappingStrategy`, and then, lookup `mapping_infos` to get the actual `HashMappingInfo`, right?
> > Hmmm, why not just use a 1-layer lookup, i.e. table_id to `HashMappingInfo` directly?
> 
> Yes. IMO a number of tables will still use the default strategy. So it's more portable to store `HashMappingInfo` according to strategy, instead of table. This **avoids altering too much data when a node joins or leaves the cluster**.
> 
> Besides, this also **allows tables to share one custom strategy**.

Theoretically we only need HashMappingInfo per fragment. However, we can have multiple tables in one fragment and we need to lookup HashMappingInfo for a table. Does this two-layer structure try to facilitate the per table lookup?

**Comment by xx01cyx** [comment]
> But the strategy is hard-coded in an `enum`, and it's not easy to make it configurable. That is, if the storage module or user decides to create a new 'strategy', how can they add this strategy into `enum HashMappingStrategy`?

Current `HashMappingStrategy` is just a simple model. We could refine this later to something like

```rust
struct HashMappingStrategy {
    node_num: Option<u32>,
    parallel_unit_percent: Option<u32>,
    ......
}
```
which is fully configurable.

**Comment by xx01cyx** [comment]
> Another reason is: imagine that we are going to support adding compute nodes on the fly, in this case, the MVs created before adding new node is running on N nodes, and the MVs created after adding new node will run on N+1 nodes. Here they use different `HashMappingInfo`, but this is not caused by different strategies - they should share the same strategy (default) to ensure they can take use of all nodes after a cluster reboot.

In this case, they'll use the same `HashMappingInfo`, since there is only one `HashMappingInfo` mapped by default strategy, and all MVs mapped to this strategy share the same hash mapping. 

That is, if two MVs share the same strategy, they'll share the same hash mapping.

**Comment by xx01cyx** [comment]
> Theoretically we only need HashMappingInfo per fragment. However, we can have multiple tables in one fragment and we need to lookup HashMappingInfo for a table. Does this two-layer structure try to facilitate the per table lookup?

You mean when doing compaction, the compactor needs per table lookup, right? There might be some differences between `TableId -> HashMappingStrategy -> HashMapping` and `TableId -> HashMapping`, but not too much, since get in HashMap is an O(1) operation. But the two-layer structure indeed saves a lot of memory space.

**Comment by fuyufjh** [comment]
> > But the strategy is hard-coded in an `enum`, and it's not easy to make it configurable. That is, if the storage module or user decides to create a new 'strategy', how can they add this strategy into `enum HashMappingStrategy`?
> 
> Current `HashMappingStrategy` is just a simple model. We could refine this later to something like
> 
> ```rust
> struct HashMappingStrategy {
>     node_num: Option<u32>,
>     parallel_unit_percent: Option<u32>,
>     ......
> }
> ```
> 
> which is fully configurable.

Hmmm, the example above make it very strange to be the key of

```
mapping_infos: HashMap<HashMappingStrategy, HashMappingInfo>,
```

**Comment by fuyufjh** [comment]
> > Another reason is: imagine that we are going to support adding compute nodes on the fly, in this case, the MVs created before adding new node is running on N nodes, and the MVs created after adding new node will run on N+1 nodes. Here they use different `HashMappingInfo`, but this is not caused by different strategies - they should share the same strategy (default) to ensure they can take use of all nodes after a cluster reboot.
> 
> In this case, they'll use the same `HashMappingInfo`, since there is only one `HashMappingInfo` mapped by default strategy, and all MVs mapped to this strategy share the same hash mapping.
> 
> That is, if two MVs share the same strategy, they'll share the same hash mapping.
> 
> ```
>   MV1                             MV2
>    |                               |
>    --->   default strategy     <---
>                   |
>   hash mapping for default strategy
> ```

In my example, since the cluster size has changed between MV1 and MV2, MV2 uses more nodes in its hash mapping, therefore, they use different mapping

**Comment by fuyufjh** [comment]
> So it's actually a tradeoff between time and space.

I can understand it, but I think it's over-designed here. Actually, even for the uncompressed mapping info, the memory usage is not a big problem and is not worth introducing a new concept 'HashMappingStrategy' for it.

**Comment by xx01cyx** [comment]
> Hmmm, the example above make it very strange to be the key of
> 
> ```
> mapping_infos: HashMap<HashMappingStrategy, HashMappingInfo>,
> ```

Indeed. Might consider adding an id for `HashMappingStrategy` and use this id as the key of HashMap.

**Comment by xx01cyx** [comment]
> I can understand it, but I think it’s over-designed here. Actually, even considering the uncompressed mapping info per table, the memory usage is not a big problem and is not worth introducing a new concept ‘HashMappingStrategy’ for it.

But we have to store the strategy somewhere. Why not store it just in `HashMappingManager`? 🤔

**Pull request closed without merging**
