### PR TITLE
fix: set initial result to 0 for count

### LINKED ISSUE #2475: Incorrect output while `count(c)` on empty relation
**Describe the bug**
Expect 0
Output NULL

**To Reproduce**

```sql
create table t1 (v1 int, v2 int);
select count(v1) from t1;
```

**Expected behavior**

0

**Additional context**

### PR DESCRIPTION
**Pull request by xxchan**
## What's changed and what's your intention?
previously it's null

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)
fix #2475

### CODE REVIEW

**Comment by TennyZhuang** [comment]
Looks a bit complicated, will review it later.

**Review by fuyufjh — APPROVED** [review]
LGTM

**Comment by skyzh** [comment]
Why not simply change the `get_output` part to return `0` if null 🤣?

**Comment by fuyufjh** [comment]
Both are okay to me

**Pull request merged**
