### PR TITLE
fix(batch): consume dml status and ensure task id always found

### PR DESCRIPTION
**Pull request by BowenXiao1999**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Fix the deterministic test found bug.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Review by wangrunji0408 — APPROVED** [review]

**Comment by BugenZhao** [comment]
Does this PR fix the deterministic e2e? Let's take a look at how long it will take with `release` or `ci-dev`. 🥰 BTW, how about making this step required? cc @wangrunji0408

**Comment by BugenZhao** [comment]
> Does this PR fix the deterministic e2e? Let's take a look at how long it will take with `release` or `ci-dev`. 🥰 BTW, how about making this step required? cc @wangrunji0408

Looks like the timeout is too strict.

https://github.com/singularity-data/risingwave/blob/c6032f5d9e4d8dce8f584841668af74b2ba6828b/ci/scripts/deterministic-e2e-test.sh#L17-L18

**Comment by wangrunji0408** [comment]
It timeouts after switching to `ci-dev`. 🥹 The time limit should be relaxed. (run time 100s on my mac, and 20s in release mode)

I'm not sure whether it's time to make it required. For example, #4505 uses a new method of tonic, which madsim doesn't support yet (but is easy to fix). In such a case, shall we block the PR until madsim gets fixed, or leave the test broken and fix it later?

**Comment by BowenXiao1999** [comment]
> It timeouts after switching to `ci-dev`. 🥹 The time limit should be relaxed. (run time 100s on my mac, and 20s in release mode)
> 
> I'm not sure whether it's time to make it required. For example, #4505 uses a new method of tonic, which madsim doesn't support yet (but is easy to fix). In such a case, shall we block the PR until madsim gets fixed, or leave the test broken and fix it later?

Compared to required, I think at least we can remove the soft failed of sslt. When it is failed, should mark with a big :no_entry_sign: so that we can track it more easily?

**Comment by wangrunji0408** [comment]
> Compared to required, I think at least we can remove the soft failed of sslt. When it is failed, should mark with a big 🚫 so that we can track it more easily?
> 
> And PR submitters have the responsiblity to check whether it's a lack of madsim or logic error

LGTM!

**Pull request merged**
