### PR TITLE
chore(ci): bump sqllogictest to v0.5.4

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title. If run successfully, we will now see sqllogictest in build kite's test analytics, so as to know which test fails frequently.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by neverchanje** [comment]
@skyzh Do you need approval? What's the problem here?

**Comment by skyzh** [comment]
Buildkite still cannot recognize sqllogictest's junit file, so I'll work on sqllogictest first.

**Review by TennyZhuang — APPROVED** [review]

**Comment by skyzh** [comment]
@mergifyio requeue

**Pull request merged**
