### PR TITLE
refactor(object store): make object store a separate crate

### PR DESCRIPTION
**Pull request by wenym1**
## What's changed and what's your intention?

Currently object store only locates in the `src/storage`, which limits its usage in other crates. This PR will move it to the `rising_common` crate so that is can be used in crate other than `risingwave_storage`. Some dependencies of the object store, such as the LRU cache and object store metrics, are also moved to `src/common`.

A potential usage at current time is using object store in `meta`. The `HummockVersion` can be huge, and is read-only. Therefore we may consider storing the `HummockVersion` object in object store instead of `etcd`, and in `etcd` we only store a reference to the object.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by fuyufjh** [comment]
> The HummockVersion can be huge, and is read-only. Therefore we may consider storing the HummockVersion object in object store instead of etcd, and in etcd we only store a reference to the object.

I think we should consider implementing the incremental version first. Metadata need to be cached in memory, so moving to etcd doesn't solve the problem.

**Comment by hzxa21** [comment]
> > The HummockVersion can be huge, and is read-only. Therefore we may consider storing the HummockVersion object in object store instead of etcd, and in etcd we only store a reference to the object.
> 
> I think we should consider implementing the incremental version first. Metadata need to be cached in memory, so moving to etcd doesn't solve the problem.

+1

**Comment by hzxa21** [comment]
Moving object store out of `storage` crate is okay but I don't think we should put it in `common`. We should keep `common` relatively small and only put common types or maybe util functions in `common` because all other crates depend on it. For example, `sqlparser` and `expr` crates depend on `common` but it doesn't make sense for them to depend on object store.

I suggest either we keep it as it is and move object store out when know object store will be used outside of `storage`, or we create a new crate for object store.

**Comment by wenym1** [comment]
I just created a new crate named `object_store` and move the object store code to the crate.

**Review by skyzh — APPROVED** [review]

**Pull request merged**
