### PR TITLE
fix(optimizer): materialize's dist should satisfies pk

### PR DESCRIPTION
**Pull request by st1page**
## What's changed and what's your intention?
materialize's dist should satisfies pk
or there might be multi executor write same pk

revert https://github.com/singularity-data/risingwave/pull/1653
## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
LGTM and looks reasonable. One small question: why materialize's dist needs to be enforced?

If the upstream ensureS that after processing, for the same pk, it won't be shuffled to different shards, we don't need to enforce distribution?

**Comment by skyzh** [comment]
For example, in https://github.com/singularity-data/risingwave/issues/1652, I guess insertion and deletion of one pk will always be shuffled to the same project, and thus same materialize node.

**Comment by st1page** [comment]
> If the upstream ensureS that after processing, for the same pk, it won't be shuffled to different shards, we don't need to enforce distribution?

I think not every upstream streaming operator should ensure that. only those operator with state requring that

**Comment by skyzh** [comment]
Let's also revert https://github.com/singularity-data/risingwave/pull/1653 in this PR?

**Comment by skyzh** [comment]
> I think not every upstream streaming operator should ensure that. only those operator with state requring that

Any examples? Still can't quite convince myself whether this works or not.

**Comment by st1page** [comment]
> Any examples? Still can't quite convince myself whether this works or not.

the different executors have different distribution requirements. and not every stateful executor requires "for the same pk, it won't be shuffled to different shards".

because the state's pk is different from its input's pk. like HashJoin/HashAgg it just requires "for the same *JoinKey/GroupKey*, it won't be shuffled to different shards". the JoinKey/GroupKey is the prefix of the state's pk.

**Comment by skyzh** [comment]
Okay, I got the point. I think join is a good example. Given `select * from a inner join b on v`,

Join's output pk is `a.pk, b.pk`. Join's distribution is by `a.v`. Therefore, currently we cannot guarantee that for the same a.pk, it will be distributed to one output.

**Pull request merged**
