### PR TITLE
feat(build): drop support for TiKV and RocksDB, and speedup compile

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

## What's changed and what's your intention?

Significantly reduce release build time (and re-compile time). Simple change in `risingwave_stream` crate should compile within 1m on M1 MacBook Pro. Debug builds will also be faster.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

partially solve .https://github.com/singularity-data/risingwave/issues/2833
partially solve .https://github.com/singularity-data/risingwave/issues/2980

### CODE REVIEW

**Review by lmatz — APPROVED** [review]
🐐

**Comment by skyzh** [comment]
image

The current build graph looks pretty good 🤪

**Comment by skyzh** [comment]
For debug builds, we can still pipeline things in the future

image

**Comment by skyzh** [comment]
Huge speedup of release mode on main:

image
image

8m47s -> 6m15s

**Pull request merged**
