### PR TITLE
chore(docker): replace host network mode to docker network

### PR DESCRIPTION
**Pull request by Gogomoe**
## What's changed and what's your intention?

Replace host network mode to docker network.
Notice that kafka-addr is set to port 29092 in docer network, and map 9092 to host.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

### CODE REVIEW

**Review by neverchanje — APPROVED** [review]
lgtm, may you add the compactor binary altogether in the docker image? Also we need to include it in docker-compose file.

**Review by tabVersion — APPROVED** [review]
LGTM

**Comment by skyzh** [comment]
> Notice that kafka-addr is set to port 29092 in docer network, and map 9092 to host.

This would be confusing? When users create source, they will specify 29092. But when they use their own tools, they will use 9092?

Also should export Redpanda's 9092 port (besides ports: 29092:9092).

**Comment by Gogomoe** [comment]
> > Notice that kafka-addr is set to port 29092 in docer network, and map 9092 to host.
> 
> This would be confusing? When users create source, they will specify 29092. But when they use their own tools, they will use 9092?
> 
> Also should export Redpanda's 9092 port (besides ports: 9092:9092).

Yes, this is confusing.
This is related to advertise-kafka-addr.
When I use `--kafka-addr 0.0.0.0:9092 --advertise-kafka-addr redpanda:9092` and map 9092, my own tools (a python script) cannot send message into redpanda.
When I use `--kafka-addr 0.0.0.0:9092 --advertise-kafka-addr 127.0.0.1:9092`, my script works but risingwave cannot connect to redpanda in container.
I think it's because container and host in different network.
And I didn't find a more suitable solution, so I follow to [Redpanda Doc](https://docs.redpanda.com/docs/quickstart/quick-start-docker/#bring-up-a-docker-compose-file)

(Actually, I'm not sure whether mapping 29092 is useless or not)

**Comment by skyzh** [comment]
> When I use --kafka-addr 0.0.0.0:9092 --advertise-kafka-addr redpanda:9092 and map 9092, my own tools (a python script) cannot send message into redpanda.

That's because your Python tool is running in host network stack, and RisingWave connects from docker.

Then maybe it's okay to export two addresses.

**Pull request merged**
