### PR TITLE
fix(state-store): fix a dead lock in memory state store

### PR DESCRIPTION
**Pull request by BowenXiao1999**
## What's changed and what's your intention?

ref #2197 . e2e test will dead lock if runs in memory state backend.

parking_lot::Mutex can also solve it. 

Can not find the root cause. I guess different actors in different spawned tasks doing operations concurrently so we get a deadlock. 

Tested locally.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
But we still don't know why the dead lock happens, right? 🤣

**Comment by BowenXiao1999** [comment]
Do we really need async lock? In what situation we can gain from the cpu yield?

**Comment by BowenXiao1999** [comment]
> But we still don't know why the dead lock happens, right? 🤣

Yes...

**Comment by skyzh** [comment]
> Do we really need async lock? In what situation we can gain from the cpu yield?

Here we indeed don't need an async lock.

**Comment by BowenXiao1999** [comment]
> > Do we really need async lock? In what situation we can gain from the cpu yield?
> 
> Here we indeed don't need an async lock.

Then I better change to parking_lot and avoid future bugs (

**Pull request merged**
