### PR TITLE
refactor(storage): remove async_trait for MergeIteratorNext

### LINKED ISSUE #3672: refactor(storage): remove async_trait for MergeIteratorNext
The trait `MergeIteratorNext` is implemented by `OrderedMergeIteratorInner` and `UnorderedMergeIteratorInner`. The usage of MergeIterators may incur frequent `next_inner` calls that implies overheads.

Refactor can be done on:
- The `MergeIteratorNext` trait
- The `OrderedMergeIteratorInner` and `UnorderedMergeIteratorInner` structs
- The lifecycle settings of `impl MergeIteratorInner`

### PR DESCRIPTION
**Pull request by KivenChen**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This PR removes async_trait for MergeIteratorNext. Changes include:

- Refactoring the MergeIteratorNext trait
- Refactoring implementations (`OrderedMergeIteratorInner` and `UnorderedMergeIteratorInner`)
- Fixing lifecycle settings.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
close #3672

### CODE REVIEW

**Comment by KivenChen** [comment]
PTAL @lmatz @wenym1

**Review by lmatz — APPROVED** [review]
LGTM!

**Review by wenym1 — APPROVED** [review]
General IGTM. 

Before merge into main, can you run the benchmark with `cargo bench --bench bench_merge_iter` to compare the merge iterator performance before and after this PR?

**Comment by Little-Wallace** [comment]
Good job! Could we remove more `async_trait` for `next` in each kind of `Iterator`?

**Pull request merged**
