### PR TITLE
feat(storage): prefetch data for compaction

### PR DESCRIPTION
**Pull request by Little-Wallace**
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>

## What's changed and what's your intention?

Our default configuration for block-size is 64 KB. But according to some tests, a larger read request can improve scan request.
image

A simple idea is reading multiple block for compactor.

Optimization:

1. prefetch multiple blocks for reading in compaction job.
2. upload the results of compaction to s3 in parallel
3. prefetch meta data before compaction task starts, because there may be a lot of files in L0 and each of them is just generated by compute-node, which can not exist in meta-cache of compactor node.

## Checklist

- [x] I have added necessary unit tests and integration tests

### CODE REVIEW

**Comment by Little-Wallace** [comment]
cc @skyzh  Maybe it can help your load data in test.

**Review by skyzh — APPROVED** [review]
If there are too many tables to compact (like L0 overlaps with a very large range of L6), will the memory overhead be too high? What I thought of prefetching is something like table iterator will automatically prefetch the next block while the current block is being read.

**Comment by Little-Wallace** [comment]
> 

Good catch.... But the problem only cause some of useless request. Because all data will be placed to block-cache and it would never exceed the capacity limit

**Comment by Little-Wallace** [comment]
The next step I will make the prefetch size configurable and user can pass key-range to ReadOptions so that we would not read data blocks which keys has exceed the target key-range.

**Comment by jon-chuang** [comment]
> I will make the prefetch size configurable

+1, but set a reasonable default (and try to benchmark the different prefetch size if possible?)

I think basically the pattern is something like an async queue that will try to fetch N blocks in advance and it can buffer N blocks?

**Comment by Little-Wallace** [comment]
> > I will make the prefetch size configurable
> 
> +1, but set a reasonable default (and try to benchmark the different prefetch size if possible?)
> 
> I think basically the pattern is something like an async queue that will try to fetch N blocks in advance and it can buffer N blocks? (so it also has built-in back pressure)
For remote compaction like s3, read  1MB-size data only cost a little more time than 48KB. So we do not need to fetch them in another thread.

**Pull request merged**
