### PR TITLE
refactor(storage): remove vnode pruning from state store and keyspace

### PR DESCRIPTION
**Pull request by xx01cyx**
### Changes

According to our offline discussion, we'll encode vnode into storage key, instead of passing it directly into keyspace and state store. Therefore, relevant interfaces should be modified. This PR do the following refactors:

- Remove vnode from keyspace
- Remove vnode from state store interfaces (get, scan, iter, etc.)
- Discard read pruning by vnode in Hummock
- Discard `struct VNodeBitmap`

### Limitations

`VNodeBitmap` in SST meta still exists. This should be discarded as well to make our compaction no longer consistent-hash-aware.

## Checklist

- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Review by soundOfDestiny — APPROVED** [review]
as PR title

**Review by fuyufjh — APPROVED** [review]
LGTM

**Comment by skyzh** [comment]
I'd like to hold this PR for a little bit. Looks like a big decision indeed 🤣

**Comment by xx01cyx** [comment]
> I'd like to hold this PR for a little bit. 

I'd like to know the concern 🤔

**Review by hzxa21 — APPROVED** [review]

**Comment by skyzh** [comment]
Thought for a moment, I have no clear idea on this change. Also thought about some edge use cases (like simple agg, MV and index), and all of them can still work without passing vnode to the storage layer to do any filtering. I think executors can still fit in the current design, with only vnode in compute layer and without vnode in storage layer.

**Comment by xxchan** [comment]
Then how does batch RowSeqScan partition? 😇

**Comment by xxchan** [comment]
BTW, does https://github.com/singularity-data/risingwave/pull/2887 also become unnecessary (executors doesn't need `vnode_bitmap`)?

**Comment by BugenZhao** [comment]
> Then how does batch RowSeqScan partition? 😇

With the vnode prepending to the key, it seems partition scan can be simply implemented with range scan with the vnode prefix?

**Comment by xxchan** [comment]
> > Then how does batch RowSeqScan partition? 😇
> 
> With the vnode prepending to the key, it seems partition scan can be simply implemented with range scan with the vnode prefix?

So each scan executor's vnodes will be a consecutive range (instead of consistent hash)?

**Comment by fuyufjh** [comment]
> > > Then how does batch RowSeqScan partition? 😇
> 
> > 
> 
> > With the vnode prepending to the key, it seems partition scan can be simply implemented with range scan with the vnode prefix?
> 
> 
> 
> So each scan executor's vnodes will be a consecutive range (instead of consistent hash)? 

As discussed in Patrick's proposal, the new row format will be like:

table_id, vnode_id, pk_columns...

Thus, partition by consistent-hashing can be represented as a set of prefix range of keys.

**Comment by xx01cyx** [comment]
> BTW, does https://github.com/singularity-data/risingwave/pull/2887 also become unnecessary (executors doesn't need vnode_bitmap)?

According to the new design, we won't rely on vnode bitmap to do read pruning or compaction, so exactly, they are not required by executors.

**Pull request merged**
