### PR TITLE
feat(streaming): use row-based encoding for agg

### PR DESCRIPTION
**Pull request by wcy-fdu**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)
close https://github.com/singularity-data/risingwave/issues/4106

### CODE REVIEW

**Review by BowenXiao1999 — COMMENTED** [review]
I only found `StateTable` -> `RowBasedStateTable` in naming. ~~Where's the encoding part?~~

**Comment by BowenXiao1999** [comment]
I think this is just a Name change. so LGTM

**Review by BowenXiao1999 — APPROVED** [review]

**Review by BugenZhao — COMMENTED** [review]
LGTM. Do we have benchmarks for this?

**Comment by wcy-fdu** [comment]
> LGTM. Do we have benchmarks for this?

For `agg` state, I think we can skip benchmark for a while, because the read/write pattens of `agg` state are all whole row.

For `join`, I'm doing the benchmark on row-based `hash join`, and will reopen the PR #4100 , showing bench results in PR #4100.

An micro benchmark on `StateStore`/`Relational Table`  will be done after all stateful executors using row-based encoding (except `materialize`). As will have compaction group now, the KV pairs of `materialize view` (cell-based) and the KV pairs of internal state (row-based) will not exists in the same SST.

**Comment by wcy-fdu** [comment]
> I only found `StateTable` -> `RowBasedStateTable` in naming. ~Where's the encoding part?~

Yes, they are using different encoding format, which impl generic `RowSerde`.
```rust
pub type StateTable<S> = StateTableBase<S, CellBasedRowSerde>;
pub type RowBasedStateTable<S> = StateTableBase<S, RowBasedSerde>;
```

**Pull request merged**
