### PR TITLE
style: fix some typos

### PR DESCRIPTION
**Pull request by cuishuang**

### CODE REVIEW

**Review by TennyZhuang — APPROVED** [review]
LGTM! Thanks

**Comment by TennyZhuang** [comment]
Please sign off CLA

**Review by Enter-tainer — APPROVED** [review]
LGTM :rocket:  Maybe we can introduce spell checkers, such as https://github.com/crate-ci/typos.

**Comment by cuishuang** [comment]
> Please sign your CLA, Thanks!

Done

**Comment by TennyZhuang** [comment]
Thanks!

**Pull request merged**
