### PR TITLE
fix(risedev): provide client-address for compactor

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

Fix https://github.com/singularity-data/risingwave/issues/4869.

## Checklist

- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

## Refer to a related PR or issue link (optional)
Fix https://github.com/singularity-data/risingwave/issues/4869.

### CODE REVIEW

**Review by hzxa21 — APPROVED** [review]
Thanks for the quick fix.

**Review by skyzh — APPROVED** [review]
The bug is ridiculous. I have no idea why we find this till now. Is it our first time to try connecting to compactors from meta nodes / compute nodes?

**Comment by skyzh** [comment]
I also suggest @Gun9niR to print a warning when client-addr is configured as default value. He'll come up with another fix.

**Comment by zwang28** [comment]
> The bug is ridiculous. I have no idea why we find this till now. Is it our first time to try connecting to compactors from meta nodes / compute nodes?

We never connect to compactor from other workers.
We spot this bug when we specify two compactors from different instances but with same port, resulting same port:ip in meta.

**Pull request merged**
