### PR TITLE
feat(CI): support cronjob for CI daily

### PR DESCRIPTION
**Pull request by tabVersion**
## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

run daily check for some heavy checks, scheduled everyday `00:00`

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)

part of #1993

### CODE REVIEW

**Review by skyzh — COMMENTED** [review]
Looks the same as `main.yml`? Why not simply add

```
schedule:
     - cron: '0 0 * * *'
```

in main.yaml?

**Comment by tabVersion** [comment]
> 

I am not sure about the trigger condition so separate it to a new file. fixed

**Comment by skyzh** [comment]
May also delete the newly-added main-cron.yaml?

**Comment by tabVersion** [comment]
> May also delete the newly-added main-cron.yaml?

There will be some tests that want to run every day instead of every push, so I want to distinguish them from main

**Review by skyzh — APPROVED** [review]

**Pull request merged**
