### PR TITLE
fix(expr, executor): Remove `RowExpression`: use `eval_row` and `unwrap_or(false)` on `Datum`, not panic on Null/None

### PR DESCRIPTION
**Pull request by jon-chuang**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?
 `RowExpression`: use `eval_row` and `unwrap_or(false)` on `Datum`, not panic on Null/None

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by TennyZhuang** [comment]
In fact I don’t know where RowExpression is used.

**Comment by TennyZhuang** [comment]
In fact I don’t know where RowExpression is used.

**Comment by yuhao-su** [comment]
We can remove the RowExpression in HashJoinExecutor and use Expression instead since we have eval_row now

**Comment by TennyZhuang** [comment]
> We can remove the RowExpression in HashJoinExecutor and use Expression instead since we have eval_row now

Can you remove it?

**Comment by jon-chuang** [comment]
Hmm, ok. I'll do it in this PR.

**Comment by yuhao-su** [comment]
LGTM!

**Review by yuhao-su — APPROVED** [review]

**Pull request merged**
