### PR TITLE
refactor(test): remove stream proto test case

### PR DESCRIPTION
**Pull request by ice1000**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

I created a unified `StreamFragmenterV2::build_graph` that redirects to `StreamFragmenter::build_graph` for now. It'll be replaced with a clearer implementation and supersede `StreamFragmenter` as planned in #3684.

For that we need to delete the stream proto, and I'm deleting the relevant test case first.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

#3684

### CODE REVIEW

**Review by st1page — APPROVED** [review]
LGTM

**Comment by ice1000** [comment]
> Merging [#4519](https://codecov.io/gh/singularity-data/risingwave/pull/4519?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=singularity-data) (https://github.com/singularity-data/risingwave/commit/557fd14f16d8a11aedcbe3f80027be15496dbaed) into [main](https://codecov.io/gh/singularity-data/risingwave/commit/14b8a0f4d8b1022439f4ec9b244020368d898533?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=singularity-data) (https://github.com/singularity-data/risingwave/commit/14b8a0f4d8b1022439f4ec9b244020368d898533) will increase coverage by 0.10%.

😮 this is unexpected but cool 🤣

**Comment by ice1000** [comment]
Is a rebase needed?

**Comment by ice1000** [comment]
image

Seems no

**Pull request merged**
