### PR TITLE
refactor(vnode bitmap): remove vnode bitmap in sst info

### PR DESCRIPTION
**Pull request by soundOfDestiny**
## What's changed and what's your intention?

remove vnode bitmap in sst info, because we no longer need that

### CODE REVIEW

**Review by hzxa21 — APPROVED** [review]

**Comment by hzxa21** [comment]
Are we also going to deprecate the HashStrategy for OverlapStrategy?

**Comment by soundOfDestiny** [comment]
> Are we also going to deprecate the HashStrategy for OverlapStrategy?

sure.

**Comment by soundOfDestiny** [comment]
> deprecate the HashStrategy for OverlapStrategy

#3331

**Comment by soundOfDestiny** [comment]
> Are we also going to deprecate the HashStrategy for OverlapStrategy?

https://github.com/singularity-data/risingwave/pull/3331

**Pull request merged**
