### PR TITLE
test(batch): introduce DataChunk::from_pretty

### PR DESCRIPTION
**Pull request by TennyZhuang**
Signed-off-by: TennyZhuang <zty0826@gmail.com>

## What's changed and what's your intention?

Similar to #2111 

Although it may not be the best solution, it's must friendly then before.

If we find a better solution such as `pretty_chunk!` macro, it's possible to write a simple script to migrate them all.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

### CODE REVIEW

**Review by wangrunji0408 — COMMENTED** [review]
It seems that we can share most of the code between `DataChunk` and `StreamChunk`

**Review by liurenjie1024 — APPROVED** [review]
LGTM

**Comment by liurenjie1024** [comment]
> It seems that we can share most of the code between `DataChunk` and `StreamChunk`

I think `StreamChunk` is just a special `DataChunk` with an `Op` column.

**Comment by TennyZhuang** [comment]
> > It seems that we can share most of the code between `DataChunk` and `StreamChunk`
> 
> I think `StreamChunk` is just a special `DataChunk` with an `Op` column.

But ops is very important so it will be hard to use if it’s not a first class citizen.

**Comment by liurenjie1024** [comment]
> 

Yes, I think we need an elegant way for this.

**Comment by TennyZhuang** [comment]
> It seems that we can share most of the code between `DataChunk` and `StreamChunk`

I prefer to find a better way to reuse all similar codes in StreamChunk and DataChunk, not in this PR.

**Pull request merged**
