### PR TITLE
feat(cache): introduce LruCacheEventListener to subscribe erasure and eviction

### PR DESCRIPTION
**Pull request by MrCroxx**
## What's changed and what's your intention?

Introduce trait `LruCacheEventListener` to subscribe erasure and eviction.

```rust
pub trait LruCacheEventListener: Send + Sync {
    type K: LruKey;
    type T: LruValue;

    /// `on_evict` is called when a cache entry is evicted by a new inserted entry.
    fn on_evict(&self, _key: &Self::K, _value: &Self::T) {}

    /// `on_erase` is called when a cache entry is removed by calling `erase`.
    fn on_erase(&self, _key: &Self::K, _value: &Self::T) {}
}
```

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
#198

### CODE REVIEW

**Comment by MrCroxx** [comment]
Found a case not covered, change to draft.

**Review by wenym1 — APPROVED** [review]
Generally LGTM. In real use case, what will be done in the `on_erase` and `on_evict`?

**Comment by MrCroxx** [comment]
> @wenym1 Generally LGTM. In real use case, what will be done in the `on_erase` and `on_evict`?

They are mainly designed for tiered cache:

- When `on_erase` is called (maybe by compaction listener after a compaction finished), the underlying tiers of caches will also erase the cache entry.
- When `on_evict` is called, the underlying tiers of caches will try to insert the evicted entry if needed.

**Comment by MrCroxx** [comment]
@Little-Wallace PTAL

**Review by Little-Wallace — APPROVED** [review]

**Pull request merged**
