### PR TITLE
WIP: feat(meta): store hummock version in object store

### PR DESCRIPTION
**Pull request by wenym1**
## What's changed and what's your intention?

Currently we store the hummock version in etcd. However, the hummock version can be large, and storing large value in etcd may increase its workload and cause performance downgrade. Hummock version is large, and read-only. Therefore, it's better to store it in object store.

In this PR, instead of storing the hummock version in etcd, we will store it in object store. In etcd we only store a `HummockVersionObjectRef`.
```
message HummockVersionObjectRef {
  uint64 id = 1;
  uint64 version_object_id = 2;
}
```
where the with `version_object_id` we can build a path in object store to retrieve the hummock version object. `version_object_id` is currently generated by the id generator in meta. We use this generator only to avoid id conflict. In the future we may use `uuid` or `nanoid` as the id generator to avoid generating object id from meta.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by skyzh** [comment]
Need bench before merging?

**Comment by wenym1** [comment]
> Need bench before merging?

Sure. The PR is not published yet.

**Review by zwang28 — COMMENTED** [review]
LGTM.
As you've mentioned we need a solid GC approach, which can handle both tracked and untracked objects.

**Comment by zwang28** [comment]
[As large hummock version is already causing problems in etcd](https://github.com/singularity-data/risingwave/issues/3054), what do you think of this PR? @Little-Wallace @hzxa21

**Comment by hzxa21** [comment]
> [As large hummock version is already causing problems in etcd](https://github.com/singularity-data/risingwave/issues/3054), what do you think of this PR? @Little-Wallace @hzxa21

We have serveral thoughts on how to improve hummock service:
1. Incremental version updates to meta store. This is to reduce burden on writes into meta store.
2. Incremental version fetches from CN. This is to reduce burden on reads from hummock service reduce burden on SST pruning on CN reads.
3. Store metadata elsewhere (one option is to store it in object store as done in this PR). This is to offload meta store.
4. Move to more efficient metadata management, as you described in your previous RFC. This is to improve our protocol.

IMO, all of them are worth trying. In terms of priority, I suggest we do 1) & 2) first before merging 3) & 4). The reason being is 1) & 2) have more direct impacts and 3) & 4) may lead to more complexity in implementing 1) & 2).

**Pull request closed without merging**
