### PR TITLE
chore(ci): tag docker image when release

### PR DESCRIPTION
**Pull request by huangjw806**
## What's changed and what's your intention?

Now we will tag 4 things:

* latest
* nightly-date if the BUILD_SOURCE is schedule/ui
* git tag (e.g. v0.1.9) if there's a tag
* git hash as `git-<sha1>`

Now we trigger the "docker.sh" from main pipeline when tag a new version.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

### CODE REVIEW

**Comment by skyzh** [comment]
What about:

* set docker pipeline to build on tag
* and merge this change? https://github.com/singularity-data/risingwave/pull/3466 🥺🤣

**Comment by huangjw806** [comment]
> What about:
> 
> * set docker pipeline to build on tag
> * and merge this change? [feat(build): tag git hash, release version, and nightly build #3466](https://github.com/singularity-data/risingwave/pull/3466) 🥺🤣

I was going to disable the scheduling of the docker pipeline, and manually trigger the docker pipeline from web, add docker push in the main pipeline.

**Comment by huangjw806** [comment]
https://github.com/singularity-data/risingwave/pull/3466 is good, we can increase the scheduling time gap of the docker pipeline, and there is no need to schedule it every day.

**Comment by skyzh** [comment]
That’s cool! Then we can go with this PR. cc @liurenjie1024 would you please help review PRs in this week? 🥵🤤😋

**Comment by liurenjie1024** [comment]
> That’s cool! Then we can go with this PR. cc @liurenjie1024 would you please help review PRs for this week? 🥵🤤😋

Sure

**Review by liurenjie1024 — APPROVED** [review]
LGTM

**Pull request merged**
