### PR TITLE
feat(frontend): support create index

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

## What's changed and what's your intention?

```
create index index_1 on t(v1);
```

... has the same effect as:

```
create materialized view index_1 as select * from t order by v1;
```

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)

close https://github.com/singularity-data/risingwave/issues/1909

### CODE REVIEW

**Comment by MrCroxx** [comment]
It means that the index name should be globally unique instead of table-grained unique?

**Comment by skyzh** [comment]
> It means that the index name should be globally unique instead of table-grained unique?

Yes. We can refactor catalog later to distinguish index and table, so that we can create per-table index.

**Comment by fuyufjh** [comment]
> > It means that the index name should be globally unique instead of table-grained unique?
> 
> Yes. We can refactor catalog later to distinguish index and table, so that we can create per-table index.

Well. I think it's reasonable for us to make index & table names globally unique

**Review by fuyufjh — APPROVED** [review]
LGTM

**Review by MrCroxx — APPROVED** [review]
LGTM

**Pull request merged**
