### PR TITLE
feat(storage): support compression setting per level

### LINKED ISSUE #2800: storage: support adjustable block compression
We have already supported lz4 compression. We should be able to support more compression methods, and be able to set compression level per layer.

- [x] support zstd encoding
- [x] support compression setting per level.

Basically, we will need to start from here:

https://github.com/singularity-data/risingwave/blob/3039172f77d5da5351e2b8fbc333fffac0c2754c/src/storage/src/hummock/sstable/block.rs#L46

### PR DESCRIPTION
**Pull request by Shmiwy**
Signed-off-by: Shmiwy <wyf000219@126.com>

## What's changed and what's your intention?

I modified the `StorageConfig` structure, adding a new member called `enable_compressiion` to indicate whether compression is allowed when creating SSTTable.

Then during compacting, if `enable_compression == true`, I get the target level from `compact_task` and determine the compression algorithm  to apply based on the level num.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

close #2800

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
LGTM!

**Comment by skyzh** [comment]
I believe this PR is not causing regression, and we can always enable / disable it with config. So maybe we can get it merged now? cc @Little-Wallace

**Comment by skyzh** [comment]
Would you please fix clippy warning before merging?

**Comment by skyzh** [comment]
Oops, did you accidentally removed your commits? This PR looks to have been automatically closed.

**Comment by Shmiwy** [comment]
It seems that I accidently touch something wrong...

**Comment by Shmiwy** [comment]
I will open a new pr later..

**Pull request closed without merging**
