### PR TITLE
feat: notify actor info when CN joined and dynamically adjust the parallelism of chain

### PR DESCRIPTION
**Pull request by yezizp2012**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title, notify global actor info when CN joined. And also dynamically adjust the parallelism of chains to its upstream, so that creating MoM after new CN joined won't fail.

image

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by yezizp2012** [comment]
TODO: We still need to resolve the following `FIXME`:   https://github.com/singularity-data/risingwave/blob/2d2b42f7a05af8088f6af799b021516a718d694f/src/meta/src/stream/stream_manager.rs#L183 

When some scaling in/out occurred (CN joined and left), we can't guarantee the assumption by the following schedule logic:
https://github.com/singularity-data/risingwave/blob/2d2b42f7a05af8088f6af799b021516a718d694f/src/meta/src/stream/scheduler.rs#L182-L185

**Comment by yezizp2012** [comment]
> TODO: We still need to resolve the following `FIXME`:
> 
> https://github.com/singularity-data/risingwave/blob/2d2b42f7a05af8088f6af799b021516a718d694f/src/meta/src/stream/stream_manager.rs#L183
> 
> When some scaling in/out occurred (CN joined and left), we can't guarantee the assumption by the following schedule logic:
> 
> https://github.com/singularity-data/risingwave/blob/2d2b42f7a05af8088f6af799b021516a718d694f/src/meta/src/stream/scheduler.rs#L182-L185

Cc @BugenZhao @shanicky , this's not that easy to resolve. I will resolve this in another PR and suggest to merge this first if it looks good to you. Because this will solve the problem that @shanicky met when doing migration test locally.

**Comment by BugenZhao** [comment]
> dynamically adjust the parallelism of chain

This works correctly since #4534.

> TODO: We still need to resolve the following FIXME

Actually, this assumption has been broken for mview on singleton upstream mview in #4153: we randomly choose a parallel unit id for downstream chain, which can be different from the upstream materialize. Therefore, the downstream compute node may also does not know about the upstream materialize actor info (since they're on different nodes), but we broadcast the info along with the create materialized view procedure so there's no problem.

So I'm doubting about whether we should apply this fix for scaling. From my prospective, the scaling procedure should be simliar to create mview, we should also resolve the upstream and downstream info in meta service, and broadcast them only **to those required compute nodes ad-hoc** but not to notify all actor info when new CN joins. Considering this case:

- CN 4 joins, get all actor info snapshot.
- Create a new mview on CN 1,2,3, so CN 4 does not know about this mview.
- Scale out some fragment to CN 4, this still doesn't work.

**Comment by BugenZhao** [comment]
IIRC, broadcasting actor info is really a old design. 🤣 If we really want to refactor the logic with notification service, we should not only handle the snapshot, but also handle all subsequent notifications.

**Comment by yezizp2012** [comment]
> IIRC, broadcasting actor info is really a old design. 🤣 If we really want to refactor the logic with notification service, we should not only handle the snapshot, but also handle all subsequent notifications.

Yes, but handling all subsequent notification of actor info does not work when create MoM. Because we don't know wether the notification has been applied or not in current implementation of notification service. Then we might fail when trying to update and build actors.

**Comment by yezizp2012** [comment]
> > dynamically adjust the parallelism of chain
> 
> This works correctly since #4534.

Well, after some new CN joined, the default parallelism will changed. When create a new mview upon an exist mview, the new one will have different parallelism for chain node with exist mview nodes. This will cause meta panic. This situation will also happen when creating a new mview upon an exist mview after some scaling(even they might have same parallelism), because currently we schedule fragment to parallel units in this way: `parallel_units.truncate(fragment.actors.len());`. They might have different parallel unit set.


> > TODO: We still need to resolve the following FIXME
> 
> Actually, this assumption has been broken for mview on singleton upstream mview in #4153: we randomly choose a parallel unit id for downstream chain, which can be different from the upstream materialize. Therefore, the downstream compute node may also does not know about the upstream materialize actor info (since they're on different nodes), but we broadcast the info along with the create materialized view procedure so there's no problem.
> 
> So I'm doubting about whether we should apply this fix for scaling. From my prospective, the scaling procedure should be simliar to create mview, we should also resolve the upstream and downstream info in meta service, and broadcast them only **to those required compute nodes ad-hoc** but not to notify all actor info when new CN joins. Considering this case:
> 
> * CN 4 joins, get all actor info snapshot.
> * Create a new mview on CN 1,2,3, so CN 4 does not know about this mview. (this will be possible in the future)
> * Scale out some fragment to CN 4, this still doesn't work.

In this case, I added a `TODO` in procedure of create MV in stream manager: we should broadcast the actor info to all nodes rather than only CN 1,2,3. So the actor info is known globally and scaling out to CN4 will works fine.
This's a good point that you mentioned, the scaling procedure should be similar to create mview and we only need to broadcast the related actor info to those required compute nodes ad-hoc.

**Comment by yezizp2012** [comment]
After some offline discussion with @BugenZhao , dynamically adjust the parallelism of chain is necessary and we decided to broadcast upstream/downstream actor info when scaling like create MoM instead of through notification services, CC @shanicky . 
To solve the chain mview node mapping problem, we should mapping the upstream mview actor according to its vnode range rather than its parallel unit id. I will submit a new PR later.

**Pull request closed without merging**
