### PR TITLE
fix(risedev): cannot `d` after adding shared in-memory hummock support 

### LINKED ISSUE #4351: risedev: cannot start with `./risedev d`
cc @BugenZhao looks like a bug 🥵🥵🥵

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As title.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- Close #4351 
- Resolve the comments about compactor in #4332

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
Looks good!

**Comment by skyzh** [comment]
Also close https://github.com/singularity-data/risingwave/pull/4352#issuecomment-1201220102?

**Review by Li0k — APPROVED** [review]
LGTM!!!

**Comment by Li0k** [comment]
> Also close #4352?

close it

**Pull request merged**
