### PR TITLE
refactor(batch): Refactor batch task context for execution.

### PR DESCRIPTION
**Pull request by liurenjie1024**
## What's changed and what's your intention?

In this PR we add a trait `BatchTaskContext` so that we can provide different executor execution/task context. Since we need to add support for local executor mode, which will construct executors in frontend (currently we only construct it in compute node), so we need to abstract out the execution context for different execution environments.

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

### CODE REVIEW

**Comment by fuyufjh** [comment]
Perhaps you need to make the PR description more detailed, such as the motivation and context.  I believe the other reviewer won't understand 🤣

**Comment by liurenjie1024** [comment]
> Perhaps you need to make the PR description more detailed, such as the motivation and context. I believe the other reviewers won't understand why 🤣

Fixed.

**Review by neverchanje — APPROVED** [review]
lgtm, I feel we can have the trait BatchTaskContext somewhat simpler after we implement other context type and see how.

**Comment by liurenjie1024** [comment]
> 

Agree. I would postpone the simplification process later to avoid too complex PR.

**Comment by fuyufjh** [comment]
I think we may start from simple queries like point queries and lookup joins. This PR implicitly make **all** operators ready for local execution mode, which looks somehow too big to me.

**Comment by liurenjie1024** [comment]
> 

I think according to our design, almost all executors should be able to run in both mode, they just need to be provide different context.

**Pull request merged**
