### PR TITLE
test(bench): introduce bench tool for the file cache system

### PR DESCRIPTION
**Pull request by MrCroxx**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

As titled, introduce bench tool for the file cache system.

Quick Startup:

```bash
cargo run --release --package risingwave_bench --bin file-cache-bench -- -p /<path>/<to>/<file>/<cache>
```

Usage:
```plain
risingwave_bench

USAGE:
    file-cache-bench [OPTIONS] --path <PATH>

OPTIONS:
        --bs <BS>                                                  [default: 1048576]
        --cache-file-fallocate-unit <CACHE_FILE_FALLOCATE_UNIT>    [default: 67108864]
        --capacity <CAPACITY>                                      [default: 1073741824]
        --concurrency <CONCURRENCY>                                [default: 8]
    -h, --help                                                     Print help information
        --look-up-range <LOOK_UP_RANGE>                            [default: 10000]
    -p, --path <PATH>
        --read <READ>                                              [default: 1]
        --report-interval <REPORT_INTERVAL>                        [default: 1]
        --time <TIME>                                              [default: 600]
        --total-buffer-capacity <TOTAL_BUFFER_CAPACITY>            [default: 134217728]
        --write <WRITE>                                            [default: 1]
```

Output example:
```plain
Total:
disk total iops: 1459.7
disk total throughput: 361.2 MiB/s
disk read iops: 1344.6
disk read throughput: 334.8 MiB/s
disk write iops: 115.1
disk write throughput: 26.4 MiB/s
insert iops: 26.4/s
insert throughput: 26.4 MiB/s
insert lat p50: 4us
insert lat p90: 6us
insert lat p99: 10us
get iops: 343.1/s
get miss: 0.00%
get hit lat p50: 1527us
get hit lat p90: 4159us
get hit lat p99: 5791us
get miss lat p50: 0us
get miss lat p90: 0us
get miss lat p99: 0us
flush iops: 20.3/s
flush throughput: 26.4 MiB/s
```

To monitor:
- [x] Disk (partition) io statics where the cache dir locates.
- [x] CURD critical path latency.
- [x] Foreground operation statics.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
#198
#3556

### CODE REVIEW

**Comment by MrCroxx** [comment]
Calculating quantiles seems suffer from a performance issue after long running. Investigating the cause.

**Comment by MrCroxx** [comment]
The get hit latency looks high. I'll run a `fio` to find the issue.

**Comment by MrCroxx** [comment]
An observation is that: When the disk pressure is high, the latency is mush higher. But because of the bandwidth limitation, the read throughput is no longer increasing. And the latency can be even higher than S3.

FYI: ScyllaDB has found the disk character before. See: https://www.scylladb.com/2018/04/19/scylla-i-o-scheduler-3/

To solve the problem, IMO, we can introduce an IO scheduler:

1. If the read workload overwhelms the disk ability, redirect the read requests to S3 to reduce the disk pressure.
2. Control the IO quota between put and get to reduce coherent influences.

There's not only bad news, because we cannot tell how badly the read/write workload is for the file cache system. Maybe we can simply introduce a threshold for IOs.

**Comment by MrCroxx** [comment]
With a limited rate, the latency can be much better:

--default
```
Total:
disk total iops: 1559.9
disk total throughput: 382.7 MiB/s
disk read iops: 264.8
disk read throughput: 66.1 MiB/s
disk write iops: 1295.1
disk write throughput: 316.6 MiB/s
insert iops: 13043.8/s
insert throughput: 12.7 GiB/s
insert lat p50: 5us
insert lat p90: 9us
insert lat p99: 45us
get iops: 13043.8/s
get miss: 98.34%
get hit lat p50: 2975us
get hit lat p90: 20479us
get hit lat p99: 132095us
get miss lat p50: 4us
get miss lat p90: 7us
get miss lat p99: 707us
flush iops: 5.0/s
flush throughput: 315.2 MiB/s
```

--loop-min-interval 150 --read 13 --write 1 --concurrency 4
```
Total:
disk total iops: 1459.7
disk total throughput: 361.2 MiB/s
disk read iops: 1344.6
disk read throughput: 334.8 MiB/s
disk write iops: 115.1
disk write throughput: 26.4 MiB/s
insert iops: 26.4/s
insert throughput: 26.4 MiB/s
insert lat p50: 4us
insert lat p90: 6us
insert lat p99: 10us
get iops: 343.1/s
get miss: 0.00%
get hit lat p50: 1527us
get hit lat p90: 4159us
get hit lat p99: 5791us
get miss lat p50: 0us
get miss lat p90: 0us
get miss lat p99: 0us
flush iops: 20.3/s
flush throughput: 26.4 MiB/s
```

So IMO the key point is:
1. limit I/O rate
2. reads should have higher priority than writes, overwhelming reads can be scheduled directly to S3

**Review by hzxa21 — APPROVED** [review]

**Pull request merged**
