### PR TITLE
refactor(frontend): Move partition pruning logic to common crate

### PR DESCRIPTION
**Pull request by Graphcalibur**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
    - Move partition pruning and location logic to the common crate (previously was in frontend crate)

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
#3799

### CODE REVIEW

**Comment by lmatz** [comment]
seems the original one in `worker_node_manager.rs` doesn't get deleted, is this intended?

**Review by lmatz — COMMENTED** [review]
rest LGTM

**Comment by Graphcalibur** [comment]
> seems the original one in `worker_node_manager.rs` doesn't get deleted, is this intended?

Whoops, should be fixed now

**Review by lmatz — APPROVED** [review]

**Comment by lmatz** [comment]
Can add a mergify/can-merge label to let the pr merged automatically. @Graphcalibur

**Pull request merged**
