### PR TITLE
refactor: use state table catalog for lookup

### PR DESCRIPTION
**Pull request by BowenXiao1999**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

As title

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Documentation

If your pull request contains user-facing changes, please specify the types of the changes, and create a release note. Otherwise, please feel free to remove this section.

### Types of user-facing changes

Please keep the types that apply to your changes, and remove those that do not apply.

* Installation and deployment 
* Connector (sources & sinks)
* SQL commands, functions, and operators
* RisingWave cluster configuration changes
* Other (please specify in the release note below)

### Release note

Please create a release note for your changes. In the release note, focus on the impact on users, and mention the environment or conditions where the impact may occur.

### CODE REVIEW

**Comment by BowenXiao1999** [comment]
I'm thinking of use `StorageTable<READ_ONLY>` instead of `StateTable`. cuz the Lookup will not write into that state table and it works just like Point Scan. cc @BugenZhao , @skyzh what do you think?

**Comment by BugenZhao** [comment]
> I'm thinking of use `StorageTable<READ_ONLY>` instead of `StateTable`. cuz the Lookup will not write into that state table and it works just like Point Scan. cc @BugenZhao , @skyzh what do you think?

+1. This should be very similar to batch scan.

**Comment by BowenXiao1999** [comment]
Create two issues:
#3821 
#3820 

Leave these to future to keep this PR simple.

**Review by skyzh — APPROVED** [review]
LGTM as long as it passes unit tests.

**Review by BugenZhao — APPROVED** [review]
LGTM as long as it passes e2e tests.

**Pull request merged**
