### PR TITLE
fix(ci): exclude sqlsmith tests from coverage

### PR DESCRIPTION
**Pull request by kwannoel**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

- Exclude sqlsmith tests from coverage by:
  - Running usual test workflow with coverage (no sqlsmith included)
  - Running sqlsmith tests without coverage

## Why is this PR needed?

Currently for code coverage check:
- PRs which do not modify sqlsmith src files will decrease coverage, since sqlsmith tests do not run.
  - See https://github.com/singularity-data/risingwave/pull/4236#issuecomment-1196649361, as well as [88351f0](https://github.com/singularity-data/risingwave/pull/4231/commits/88351f05bdafb53535f1eb2e32bfc2f670d25362) from this PR.
- PRs which modify sqlsmith src files may continue increasing coverage.
- Better to just remove sqlsmith tests from coverage, anyway their code coverage is inconsistent, since queries are generated randomly.

## Does this PR work?

This commit below https://github.com/singularity-data/risingwave/pull/4231/commits/ef57c2b8ae2194051bcb7244311f682a77f501bf checks if the workflow works as expected, when running sqlsmith workflow as well. 
The coverage results from that commit shows that even if new sqlsmith workflow is triggered, they no longer increase coverage.

Coverage result before: https://github.com/singularity-data/risingwave/runs/7538862322, `73.93% (-0.11%) compared to f690d5e`
Coverage result after: https://github.com/singularity-data/risingwave/runs/7542854221, `73.93% (-0.11%) compared to f690d5e`

## Checklist

~~- [x] I have written necessary rustdoc comments~~
~~- [x] I have added necessary unit tests and integration tests~~
~~- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)~~

## Refer to a related PR or issue link (optional)

### CODE REVIEW

**Comment by kwannoel** [comment]
There's no issue, it does not run sqlsmith tests.

My suspicion is that coverage might be affected for prs which do not run sqlsmith workflow.
IF that's the case, sqlsmith tests should probably be excluded from coverage.

**Comment by kwannoel** [comment]
Updating this PR. Use to fix coverage issue.

**Comment by kwannoel** [comment]
Please feel free to suggest a better approach, if any.

**Review by skyzh — APPROVED** [review]

**Comment by kwannoel** [comment]
See if mergify can merge (does code coverage block merging? :eyes: )

**Pull request merged**
