### PR TITLE
feat(frontend): support explain create index

### LINKED ISSUE #3226: Support explain create index
```
dev=> create table t1 (v1 int);
CREATE_TABLE
dev=> explain create index i1 on t1(v1);ERROR:  Feature is not yet implemented: unsupported statement CreateIndex { name: ObjectName([Ident { value: "i1", quote_style: None }]), table_name: ObjectName([Ident { value: "t1", quote_style: None }]), columns: [OrderByExpr { expr: Identifier(Ident { value: "v1", quote_style: None }), asc: None, nulls_first: None }], unique: false, if_not_exists: false }, No tracking issue
dev=> \q
```

### PR DESCRIPTION
**Pull request by kwannoel**
## What's changed and what's your intention?

As per title.

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)
- Add the 'user-facing changes' label if your PR contains changes that are visible to users (optional)

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

closes #3226

### CODE REVIEW

**Review by xiangjinwu — APPROVED** [review]
lgtm. What about adding an e2e test (`statement ok`) to make sure it does not regress?

**Review by skyzh — APPROVED** [review]

**Comment by hengm3467** [comment]
@kwannoel I think this is a user-facing change. Correct? Thanks.

**Comment by skyzh** [comment]
Yes, added a label

**Comment by kwannoel** [comment]
> @kwannoel I think this is a user-facing change. Correct? Thanks.

Yes, sorry I missed that out.

**Comment by hengm3467** [comment]
> > @kwannoel I think this is a user-facing change. Correct? Thanks.
> 
> Yes, sorry I missed that out.

@kwannoel  No. That's totally OK. I'll be improving the note / message in the PR template about adding this label. As of now, it's not that obvious and can be easily missed. :)

**Pull request merged**
