### PR TITLE
feat(batch): Support Left Anti and Left Semi joins for Lookup Join

### LINKED ISSUE #3822: batch: Support LeftSemi and LeftAnti join types for Lookup Join

### PR DESCRIPTION
**Pull request by Graphcalibur**
I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
    - Add support for Left Anti / Left Semi joins for Lookup Joins
    - Note: The implementation of the join logic is convoluted and should probably be streamlined in a future PR similarly to Nested join, but for now this is fine.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
Fixes #3822

### CODE REVIEW

**Review by liurenjie1024 — APPROVED** [review]
LGTM!

**Comment by hengm3467** [comment]
I think this PR contains user facing changes. Correct me if I'm wrong. @Graphcalibur

**Comment by liurenjie1024** [comment]
cc @hengm3467  No, it's an optimization and hidden by optimizer.

**Comment by hengm3467** [comment]
> cc @hengm3467 No, it's an optimization and hidden by optimizer.

@liurenjie1024  Thanks for the clarification. Then I'll close the doc issue that I created earlier.

**Pull request merged**
