### PR TITLE
chore: add a new checklist item in the PR template

### PR DESCRIPTION
**Pull request by hengm3467**
Adding a new checklist item to allow contributors to indicate that their PRs contain user-visible changes, so that writers can update the user docs accordingly. 

## What's changed and what's your intention?

Added a new checklist item to allow contributors to indicate whether their PRs contain user-visible changes. This will help the writers track these type of changes and update the (external) docs accordingly. 

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [ ] I have written necessary docs and comments
- [ ] I have added necessary unit tests and integration tests

### CODE REVIEW

**Review by neverchanje — COMMENTED** [review]
I think the common practice is using github label. We can add a label called "user-facing" or else and let the devs know if it's user-facing, they should add this label.

**Comment by skyzh** [comment]
1. current CI requires all checks to be selected, so it's impossible to introduce a check that "might be selected".
2. it's hard to filter PR by checks in body.

**Comment by hengm3467** [comment]
> 1. current CI requires all checks to be selected, so it's impossible to introduce a check that "might be selected".
> 2. it's hard to filter PR by checks in body.

Thanks. Makes sense. I'll add a label, and remind contributors in this template to use it for this type of changes.

**Comment by hengm3467** [comment]
> I think the common practice is using github label. We can add a label called "user-facing" or else and let the devs know if it's user-facing, they should add this label.

Cool. Let's use labels then.

**Pull request closed without merging**
