### PR TITLE
feat(frontend): add new IndexDeltaJoin rule

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

## What's changed and what's your intention?

This PR is a step towards migrating delta join rewriter into the frontend. Currently, the rule is not enabled by default. We will do this migration step by step.

If the rule gets enabled, the plan will be like:

```yaml
- sql: |
    create table t1 (v1 int, v2 float);
    create table t2 (v3 int, v4 numeric, v5 bigint);
    create index t1_v1 on t1(v1);
    create index t2_v3 on t2(v3);
    /* should generate delta join plan, and stream index scan */
    select * from t1, t2 where t1.v1 = t2.v3;
  optimized_logical_plan: |
    LogicalLookupUnion
      LogicalJoin { type: Inner, on: ($0 = $2) }
        LogicalScan { table: t1, columns: [v1, v2] }
        LogicalScan { table: t2, columns: [v3, v4, v5] }
      LogicalProject { exprs: [$3, $4, $0, $1, $2] }
        LogicalJoin { type: Inner, on: ($3 = $0) }
          LogicalScan { table: t2, columns: [v3, v4, v5] }
          LogicalScan { table: t1, columns: [v1, v2] }
- id: 3-way-join-one-key
  sql: |
    create table a (v1 int, v2 int);
    create table b (vb int);
    create table c (vc int);
    create index a_v1 on a(v1);
    create index a_v2 on a(v2);
    create index b_vb on b(vb);
    create index c_vc on c(vc);
    /* filter is not added, tracked at https://github.com/singularity-data/risingwave/issues/2711 */
    select * from a, b, c where a.v1 = b.vb and a.v1 = c.vc /* and a.v1 > 10 and b.vb > c.vc */;
  optimized_logical_plan: |
    LogicalLookupUnion
      LogicalJoin { type: Inner, on: ($0 = $3) }
        LogicalJoin { type: Inner, on: ($0 = $2) }
          LogicalScan { table: a, columns: [v1, v2] }
          LogicalScan { table: b, columns: [vb] }
        LogicalScan { table: c, columns: [vc] }
      LogicalProject { exprs: [$1, $2, $0, $3] }
        LogicalJoin { type: Inner, on: ($1 = $3) }
          LogicalJoin { type: Inner, on: ($1 = $0) }
            LogicalScan { table: b, columns: [vb] }
            LogicalScan { table: a, columns: [v1, v2] }
          LogicalScan { table: c, columns: [vc] }
      LogicalProject { exprs: [$1, $2, $3, $0] }
        LogicalJoin { type: Inner, on: ($1 = $3) }
          LogicalJoin { type: Inner, on: ($1 = $0) }
            LogicalScan { table: c, columns: [vc] }
            LogicalScan { table: a, columns: [v1, v2] }
          LogicalScan { table: b, columns: [vb] }
- id: 3-way-join-two-keys
  sql: |
    create table a (v1 int, v2 int);
    create table b (vb int);
    create table c (vc int);
    create index a_v1 on a(v1);
    create index a_v2 on a(v2);
    create index b_vb on b(vb);
    create index c_vc on c(vc);
    /* filter is not added, tracked at https://github.com/singularity-data/risingwave/issues/2711 */
    select * from a, b, c where a.v1 = b.vb /* and a.v2 = c.vc and a.v1 > 10 and b.vb > c.vc */;
  optimized_logical_plan: |
    LogicalJoin { type: Inner, on: true }
      LogicalJoin { type: Inner, on: ($0 = $2) }
        LogicalScan { table: a, columns: [v1, v2] }
        LogicalScan { table: b, columns: [vb] }
      LogicalScan { table: c, columns: [vc] }
- id: index_slt
  sql: |
    create table iii_t1 (v1 int, v2 int);
    create table iii_t2 (v3 int, v4 int);
    create table iii_t3 (v5 int, v6 int);
    create materialized view iii_mv1 as select * from iii_t1, iii_t2, iii_t3 where iii_t1.v1 = iii_t2.v3 and iii_t1.v1 = iii_t3.v5;
    create index iii_index_1 on iii_t1(v1);
    create index iii_index_2 on iii_t2(v3);
- before:
    - index_slt
  sql: |
    select * from iii_t1, iii_t2 where iii_t1.v1 = iii_t2.v3;
  optimized_logical_plan: |
    LogicalLookupUnion
      LogicalJoin { type: Inner, on: ($0 = $2) }
        LogicalScan { table: iii_t1, columns: [v1, v2] }
        LogicalScan { table: iii_t2, columns: [v3, v4] }
      LogicalProject { exprs: [$2, $3, $0, $1] }
        LogicalJoin { type: Inner, on: ($2 = $0) }
          LogicalScan { table: iii_t2, columns: [v3, v4] }
          LogicalScan { table: iii_t1, columns: [v1, v2] }
- before:
    - index_slt
  sql: |
    select v4 from iii_t1, iii_t2 where iii_t1.v1 = iii_t2.v3;
  optimized_logical_plan: |
    LogicalLookupUnion
      LogicalProject { exprs: [$2] }
        LogicalJoin { type: Inner, on: ($0 = $1) }
          LogicalScan { table: iii_t1, columns: [v1] }
          LogicalScan { table: iii_t2, columns: [v3, v4] }
      LogicalProject { exprs: [$1] }
        LogicalJoin { type: Inner, on: ($2 = $0) }
          LogicalScan { table: iii_t2, columns: [v3, v4] }
          LogicalScan { table: iii_t1, columns: [v1] }
```

Where `LogicalJoin` and `LogicalScan` will be rewritten into `Lookup` and `IndexScan` separately, in future PRs.

The new `IndexDeltaJoin` rule is applied after MultiJoin rule and before Reorder rule. It will look for multi way joins, and try converting them into delta join plans by looking at the indices and using the delta join solver.

There are also some other changes including:

* Derive schema and pk for multi join. Otherwise no optimizer rule other than JoinReorder will be able to run after MultiJoin.
* Fix some comments
* Add a new LookupUnion node (maybe rename to Union in the future?)

## Checklist

- [x] I have written necessary docs and comments
- [x] I have added necessary unit tests and integration tests

## Refer to a related PR or issue link (optional)

https://github.com/singularity-data/risingwave/issues/2688

### CODE REVIEW

**Comment by skyzh** [comment]
need rebase after https://github.com/singularity-data/risingwave/pull/2687

**Comment by skyzh** [comment]
> Why not directly convert to physical operators?

So do we allow a plan at logical stage to have both Stream plan nodes and Logical plan nodes? If so, things indeed will become easier for me.

**Comment by st1page** [comment]
Maybe we can implement it in `LogicalMultiJoin::to_stream`, and in that case, we have 2 choice
1. prune columns and predicate push down on the stream plan
2. prune columns and predicate push down for logical multi join

**Comment by fuyufjh** [comment]
Shall we close this?

**Pull request closed without merging**
